### PR TITLE
Mike/2920 fix entry only users seeing add patient button

### LINKED ISSUE #2920: [BUG] Entry only users are seeing "add new person" button
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Entry only users are seeing the "add new person" button if someone isn't in the org, but they don't actually have permission to add new users, so clicking the button just flashes and reloads the app.

Conduct test _ SimpleReport
 

### Steps To Reproduce

1. Spoof an entry-only user (can do on local)
2. Look up someone who isn't in the org, click "add new person"
3. See site reload but button takes you nowhere

### Expected Behavior

The button shouldn't appear for entry-only users, because they don't have the ability to add folks.

### Additional context

_No response_

### Does this issue have a priority label?

- [X] I have added a priority label

### Has issue been assigned to a team?

- [X] I have added a team label

### PR DESCRIPTION
**Pull request by mpbrown**
# FRONTEND PULL REQUEST

## Related Issue

- Resolves #2920 

## Changes Proposed

- The "Add New Patient" button should only appear to users who have the _EditPatient_ permission (i.e. entry only users should not be able to see this button)
- Adds `useTypedSelector` hook as a typed version of the Redux `useSelector` hook

## Additional Information

- Updated the relevant regressions tests and Storybook stories to use `canEditPeople` prop
- Refactored the change to handle the permission check in TestQueue and pass it down as a prop to grandchild SearchResults, instead of originally using the Redux selector directly within SearchResults itself
- Not sure yet what our conventions are on renaming files, but it would be nice to add some fixes for consistency (`AddToQueueSearch.tsx` currently exports `AddToQueueSearchBox` and the tests for that component are defined in `AddToQueueSearch-patient-search.test.tsx` instead of simply `AddToQueueSearch.test.tsx`)

## Testing

- Validate that all regression tests pass
- Test that as at least a standard user, you can still access Add New Patient within the search box on the Conduct Tests page
- Test that as an entry only user, you cannot access the Add New Patient button on that page
- Test that `Search Results` stories on the Storybook are all working as expected

### CODE REVIEW

File: frontend/src/app/utils/hooks.tsx [hunk 1]
```diff
@@ -39,4 +42,6 @@ const useDocumentTitle = (title: string, retainOnUnmount = false) => {
   }, [retainOnUnmount, title]);
 };
 
-export { useOutsideClick, useDocumentTitle };
+const useTypedSelector: TypedUseSelectorHook<RootState> = useSelector;
```
Comment (johanna-skylight) [inline frontend/src/app/utils/hooks.tsx:45]: Suggestion to move this hook  to the store.ts file so all related store logic is centralized. It could also be renamed to useAppSelector so we follow the[ react-redux guide](https://redux.js.org/usage/usage-with-typescript#typing-the-useselector-hook).

**Review by johanna-skylight — COMMENTED** [review]
Looks good in general! I left two comments with suggestions.

File: frontend/src/app/utils/hooks.tsx (hunk 1 above)
Comment (mpbrown) [reply frontend/src/app/utils/hooks.tsx:45]: Yeah that makes sense to move it to store.ts. For the name of it I originally wrote it as `useAppSelector` like the guide mentions, but wasn't sure whether the name was descriptive enough. I'll update it back since the guide seems to have that as a specific naming convention for `useAppSelector` and `useAppDispatch`

**Comment by mpbrown** [comment]
Updated with the naming changes!

**Review by johanna-skylight — APPROVED** [review]
LGTM! good work 👍

**Review by nathancrtr — APPROVED** [review]
Tested locally and LGTM! :clap:
