### PR TITLE
bob/3986 fix trashcan icon

### LINKED ISSUE #3986: Trash can icon in patient self-reg needs a fix
## Area or Component
Patient Experience - Self registration

## Quick Summary
There's a trash can icon for emails in patient self-registration (and the add/edit patient flows.) This icon is hidden from screenreaders, but does provide occasional functionality if an email has been input.

The larger issue here is that the button behavior is inconsistent. If the field is blank and you click the button, nothing happens. If the field is partially filled out, it clears. If there are multiple email fields, it allows you to remove the field entirely.

## Accessibility Violation
Two:
aria-hidden="true" is used on informative content making it inaccessible to assistive technology. https://axe.deque.com/rule-help/en/semantic-hidden
The text alternative is missing. https://axe.deque.com/rule-help/en/alt-text-missing

## Action Requested
Needs design input, but my guess is that we should change the behavior of this icon or remove it (display=none) until there's more than one email address. 

## Screencast
SimpleReport (6)

## Source Code (optional)
https://github.com/CDCgov/prime-simplereport/blob/c3e6b2dc330021e425e01657eaee613c51f9e11c/frontend/src/app/patients/Components/PersonForm.tsx

Note: This is likely going to be solved at the `PersonForm` level, meaning we also need to check the in-app `Add/Edit Person` page since the component is shared.

## Original Deque Issue
semantic-hidden | aria-hidden="true" is used on informative content making it inaccessible to assistive technology. | Trash can icon has aria-hidden true for emails. The icon is actually not usable for the first email entry, so the preferred solution would be to take it off entirely vs having an incorrect icon/label | aria-hidden="true" is used incorrectly | https://axe.deque.com/rule-help/en/semantic-hidden | critical | Yes | No | Images | ["body > div#root:nth-of-type(1) > div.bg-base-lightest.minh-viewport:nth-of-type(1) > div.bg-base-lightest:nth-of-type(3) > div#registration-container.grid-container.maxw-tablet.padding-y-3:nth-of-type(1) > div.prime-formgroup:nth-of-type(2) > fieldset.usa-fieldset:nth-of-type(1) > div.usa-form:nth-of-type(2) > div.usa-form:nth-of-type(1) > div:nth-of-type(1) > div.display-flex:nth-of-type(1) > div.flex-align-self-end:nth-of-type(2) > button.usa-button--unstyled.padding-105.height-5:nth-of-type(1) > svg.svg-inline--fa.fa-trash.fa-w-14.text-error:nth-of-type(1)"] | aria-hidden="true" is used on informative content making it inaccessible to assistive technology. | <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="trash" class="svg-inline--fa fa-trash fa-w-14 text-error" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"> | wcag2a,wcag131a,wcag132a | rnv7@cdc.gov | Patient Self-Registration - Form | https://stg.simplereport.gov/app/register/9C7BB |   | 2022-07-13T22:23:43.940Z
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
alt-text-missing | The text alternative is missing. | No alt text for the trash can icon | Text alternative is missing | https://axe.deque.com/rule-help/en/alt-text-missing | critical | Yes | No | Images | ["body > div#root:nth-of-type(1) > div.bg-base-lightest.minh-viewport:nth-of-type(1) > div.bg-base-lightest:nth-of-type(3) > div#registration-container.grid-container.maxw-tablet.padding-y-3:nth-of-type(1) > div.prime-formgroup:nth-of-type(2) > fieldset.usa-fieldset:nth-of-type(1) > div.usa-form:nth-of-type(2) > div.usa-form:nth-of-type(1) > div:nth-of-type(1) > div.display-flex:nth-of-type(1) > div.flex-align-self-end:nth-of-type(2) > button.usa-button--unstyled.padding-105.height-5:nth-of-type(1) > svg.svg-inline--fa.fa-trash.fa-w-14.text-error:nth-of-type(1)"] | The text alternative is missing. | <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="trash" class="svg-inline--fa fa-trash fa-w-14 text-error" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"> | wcag2a,wcag111a,wcag111b,wcag111f | rnv7@cdc.gov | Patient Self-Registration - Form | https://stg.simplereport.gov/app/register/9C7BB |   | 2022-07-13T22:23:43.969Z

### PR DESCRIPTION
**Pull request by fzhao99**
# FRONTEND PULL REQUEST

## Related Issue

Fixes #3986 

## Changes Proposed

- Conditionally shows the trashcan icon the email form only when additional emails are present

## Additional Information

- Adds some additional labeling to the email form when relevant (ok'ed by @lauraykerr)
- Minor styling tweak to the get the input forms to align (ok'ed by @kenieh)

## Testing

- Navigate to the patient self reg/editing form
- Add optional email
- Notice trashcan icon only populates for additional fields unlike before

## Screenshots / Demos

https://user-images.githubusercontent.com/29645040/183710398-a77bcdb7-ec51-4549-a862-5269c63cdd8a.mov

### Design
- [x] Any UI/UX changes have a designer as a reviewer, and changes have been approved

### Content
- [x] Any content changes have been approved by content team

### CODE REVIEW

File: frontend/src/lang/es.ts [hunk 1]
```diff
@@ -151,6 +151,7 @@ export const es: LanguageConfig = {
           addNumber: "Agregar otro número",
           addEmail: "Agregue otra dirección de correo electrónico",
           email: "Dirección de correo electrónico",
+          additionalEmail: "Dirección de correo electrónico",
```
Comment (georgehager) [inline frontend/src/lang/es.ts:154]: Do we have a more specific string for additionalEmail? It's the same for both email and additionalEmail on es.ts, is that intentional?

**Review by georgehager — APPROVED** [review]

**Comment by georgehager** [comment]
lgtm! just a tiny comment on the `es.ts` above.

**Comment by fzhao99** [comment]
awaiting "additional email" translation from @lauraykerr before merge

**Comment by lauraykerr** [comment]
@fzhao99 Translation for additional email address: `Dirección de correo electrónico adicional`

File: frontend/src/app/patients/Components/ManageEmails.tsx [hunk 2]
```diff
@@ -136,15 +144,20 @@ const ManageEmails: React.FC<Props> = ({
...
-                <FontAwesomeIcon icon={"trash"} className={"text-error"} />
-              </button>
-            </div>
+            {idx > 0 ? (
+              <div className="flex-align-self-end">
+                <button
+                  className="usa-button--unstyled padding-105 height-5"
+                  data-testid={`delete-email-${idx}`}
+                  onClick={() => onEmailRemove(idx)}
+                  aria-label={`Delete email ${email}`.trim()}
```
Comment (emyl3) [inline frontend/src/app/patients/Components/ManageEmails.tsx:153]: If we wanted to trim the whitespace from the user inputted email value I think we have to do `Delete email ${email.trim()}`

File: frontend/src/app/patients/Components/ManageEmails.tsx [hunk 3]
```diff
@@ -136,15 +144,20 @@ const ManageEmails: React.FC<Props> = ({
...
-                onClick={() => onEmailRemove(idx)}
-                aria-label={`Delete email ${email}`.trim()}
-              >
-                <FontAwesomeIcon icon={"trash"} className={"text-error"} />
-              </button>
-            </div>
+            {idx > 0 ? (
+              <div className="flex-align-self-end">
+                <button
+                  className="usa-button--unstyled padding-105 height-5"
```
Comment (emyl3) [inline frontend/src/app/patients/Components/ManageEmails.tsx:150]: I think this issue was there before but could we add a `cursor-pointer` class to this `<button>` so there are some visual indicators that the trash can is a button?

**Review by emyl3 — COMMENTED** [review]
Just a couple things! Nice work on this, Bob! 😸

File: frontend/src/app/patients/ManagePatients.scss [hunk 4]
```diff
@@ -27,3 +27,7 @@
 .patient-form-deletion-field {
   width: calc(100% + 2.5rem);
 }
+
+.cursor-pointer {
```
Comment (emyl3) [inline frontend/src/app/patients/ManagePatients.scss:31]: I don't think you need this since `cursor-pointer` provided through uswds https://designsystem.digital.gov/utilities/

**Review by emyl3 — COMMENTED** [review]
one small thing! thank you bob!!

**Review by emyl3 — APPROVED** [review]
LGTM! 🎉

**Review by georgehager — APPROVED** [review]
nice! looks great with the additional translation.
