### PR TITLE
Adjust abnormal flag mapping

### LINKED ISSUE #7897: FHIR Mapping: Adjust abnormal flag mapping
The bug: 
A user submitting a bulk results file used a snomed code  ([10828004](https://browser.ihtsdotools.org/?perspective=full&conceptId1=10828004&edition=MAIN/2024-07-01&release=&languages=en) ) that is not accounted for by our fhir mapping logic.  This is causing the flag to get set incorrectly.  The code (Positive) should be tagged 'Abnormal'.
[Slack thread with additional context](https://skylight-hq.slack.com/archives/C0411VC78DN/p1720029558207459)

[/backend/src/main/java/gov/cdc/usds/simplereport/api/converter/FhirConverter.java#L756-L770](https://github.com/CDCgov/prime-simplereport/blob/44c3f77fb98e883213ca2dcb28ebefd9bde48e23/backend/src/main/java/gov/cdc/usds/simplereport/api/converter/FhirConverter.java#L756-L770)
```java
  private Coding convertToAbnormalFlagInterpretation(String resultCode) {
    Coding abnormalFlag = new Coding();

    abnormalFlag.setSystem(ABNORMAL_FLAGS_CODE_SYSTEM);

    if (resultCode.equals(DETECTED_SNOMED_CONCEPT.code())) {
      abnormalFlag.setCode(ABNORMAL_FLAG_ABNORMAL.code());
      abnormalFlag.setDisplay(ABNORMAL_FLAG_ABNORMAL.displayName());
    } else {
      abnormalFlag.setCode(ABNORMAL_FLAG_NORMAL.code());
      abnormalFlag.setDisplay(ABNORMAL_FLAG_NORMAL.displayName());
    }

    return abnormalFlag;
  }
```

The fix:
Expand the list of result codes we account for in the abnormal mapping to include any snomeds in the [covid](https://prime.cdc.gov/api/metadata/livd) or [hiv](https://www.cdc.gov/hiv/guidelines/reporting.html) livd tables.  We also want to adjust the mapping logic to refrain from mapping an abnormal flag if we encounter a snomed code that we do not recognize as either normal or abnormal.  Any result code that would indicate a positive test should be flagged as 'Abnormal', negative test codes should be flagged as 'Normal'.

Note:
As you are working on this ticket, try to look for anywhere else in the FHIR converter code that is mapping things based on the snomed code, especially if it is defaulting mapping behavior with an unqualified `else` block.

### PR DESCRIPTION
**Pull request by emyl3**
# BACKEND PULL REQUEST

## Related Issue

- Part 1 for #7897 
- This should at least fix the issue CA was experiencing.

## Changes Proposed

- Set the `Abnormal` and `Normal` coding only when they match a defined list of SNOMED codes that we support
- If the SNOMED code that is provided does not match, we will log it and return `null` instead of setting the code to `Normal`

## Additional Information
- Will create an alert in a separate PR when we log an unsupported SNOMED code
- ⚠️ As part of #7898 we should make sure that any results being sent to the CSV pipeline should also map to values here: https://github.com/CDCgov/prime-reportstream/blob/1ffae4ca0b04cd0aa9f169e26813ecd86df71bb5/prime-router/src/main/kotlin/metadata/Mappers.kt#L768 otherwise you get the following error from ReportStream that is not obvious to users uploading their results:
**RS CSV API Error 400 Response:**
```
{
  "id" : null,
  "submissionId" : 4261955,
  "overallStatus" : "Error",
  "timestamp" : "2024-07-11T20:43:28.954Z",
  "plannedCompletionAt" : null,
  "actualCompletionAt" : null,
  "sender" : "",
  "reportItemCount" : null,
  "errorCount" : 1,
  "warningCount" : 0,
  "httpStatus" : 400,
  "destinations" : [ ],
  "actionName" : "receive",
  "externalName" : "",
  "reportId" : null,
  "topic" : null,
  "bodyFormat" : "",
  "errors" : [ {
    "scope" : "item",
    "indices" : [ 1 ],
    "trackingIds" : [ "42daf9c8-9deb-4636-a040-380bde2b44cd+1+20240711" ],
    "field" : "test_result (test_result)",
    "message" : "The code '' for field test_result (test_result) is invalid. Reformat to HL7 specification.",
    "errorCode" : "INVALID_MSG_PARSE_CODE"
  } ],
  "warnings" : [ ],
  "destinationCount" : 0,
  "fileName" : ""
}
```

## Testing
- deployed to dev3
- upload a bulk result with various SNOMED combinations
- example with new SNOMEDs
[DEV3_EX.csv](https://github.com/user-attachments/files/16183512/DEV3_EX.csv)

### CODE REVIEW

File: backend/src/main/java/gov/cdc/usds/simplereport/api/converter/FhirConverter.java [hunk 1]
```diff
@@ -753,19 +754,21 @@
...
-    if (resultCode.equals(DETECTED_SNOMED_CONCEPT.code())) {
+    if (ABNORMAL_SNOMED_KEYS.contains(resultCode)) {
       abnormalFlag.setCode(ABNORMAL_FLAG_ABNORMAL.code());
       abnormalFlag.setDisplay(ABNORMAL_FLAG_ABNORMAL.displayName());
-    } else {
+    } else if (NORMAL_SNOMED_KEYS.contains(resultCode)) {
       abnormalFlag.setCode(ABNORMAL_FLAG_NORMAL.code());
       abnormalFlag.setDisplay(ABNORMAL_FLAG_NORMAL.displayName());
+    } else {
+      log.info("Unsupported SNOMED result code: {}", resultCode);
```
[the remark this answers is not in the document]
Comment (emyl3) [reply backend/src/main/java/gov/cdc/usds/simplereport/api/converter/FhirConverter.java]: fixed to `Encode.forJava(resultCode))` 😅

**Review by fzhao99 — DISMISSED** [review]

File: backend/src/main/java/gov/cdc/usds/simplereport/api/converter/FhirConverter.java [hunk 2]
```diff
@@ -753,19 +755,21 @@ public Observation convertToObservation(ConvertToObservationProps props) {
...
+    if (ABNORMAL_SNOMEDS.keySet().contains(resultCode)) {
       abnormalFlag.setCode(ABNORMAL_FLAG_ABNORMAL.code());
       abnormalFlag.setDisplay(ABNORMAL_FLAG_ABNORMAL.displayName());
-    } else {
+    } else if (NORMAL_SNOMEDS.keySet().contains(resultCode)) {
       abnormalFlag.setCode(ABNORMAL_FLAG_NORMAL.code());
       abnormalFlag.setDisplay(ABNORMAL_FLAG_NORMAL.displayName());
+    } else {
+      log.info("Unsupported SNOMED result code: {}", Encode.forJava(resultCode));
+      return null;
```
Comment (DanielSass) [inline backend/src/main/java/gov/cdc/usds/simplereport/api/converter/FhirConverter.java:771]: I think it also makes sense to adjust [this bit](https://github.com/CDCgov/prime-simplereport/blob/268ddb50c86572fc83419243cc36a45dfd4845a1/backend/src/main/java/gov/cdc/usds/simplereport/api/converter/FhirConverter.java#L746-L748) to not add the interpretation that the abnormal flag coding lives inside. (otherwise it will just be an empty interpretation)

**Review by mpbrown — APPROVED** [review]
LGTM! Nice work!

File: backend/src/main/java/gov/cdc/usds/simplereport/api/converter/FhirConverter.java (hunk 2 above)
Comment (mpbrown) [reply backend/src/main/java/gov/cdc/usds/simplereport/api/converter/FhirConverter.java:771]: +1 agree that makes sense to omit the interpretation if it'll be empty anyway

Comment (emyl3) [reply backend/src/main/java/gov/cdc/usds/simplereport/api/converter/FhirConverter.java:774]: OO good catch -- thank you!

**Comment by emyl3** [comment]
@fzhao99 @DanielSass @mpbrown Ready for re-review!

**Review by fzhao99 — APPROVED** [review]

**Comment by DanielSass** [comment]
>⚠️ As part of https://github.com/CDCgov/prime-simplereport/issues/7898 we should make sure that any results being sent to the CSV pipeline should also map to values here: https://github.com/CDCgov/prime-reportstream/blob/1ffae4ca0b04cd0aa9f169e26813ecd86df71bb5/prime-router/src/main/kotlin/metadata/Mappers.kt#L768 otherwise you get the following error from ReportStream that is not obvious to users uploading their results:

about this bit - is this an issue with how we are handling the response (in other words, do we need to do work to convey info we're getting from RS back to the user)?

Definitely out of scope for this PR, just something to think about as we look at the next story for updating the bulk upload file validation

**Review by DanielSass — APPROVED** [review]

**Comment by emyl3** [comment]
This is an example of a FHIR bundle with a nonsensical SNOMED (search "111") -- no abnormal/normal flag is added
[hiv_bundle_with_nonsense_snomed.json](https://github.com/user-attachments/files/16197507/hiv_bundle_with_nonsense_snomed.json)

**Review by mpbrown — APPROVED** [review]
