### PR TITLE
fix bulk uploader fhir race and ethnicity

### LINKED ISSUE #6346: [Bug] Some Race/Ethnicity are not recorded correctly in the bulk uploader FHIR
### Description
Some Race/Ethnicity are not recorded correctly in the bulk uploader FHIR

the accepted values in the bulk uploader
https://demo.simplereport.gov/app/results/upload/submit/guide?facility=a8740505-f8c0-47e4-bd1b-e21d5dea3b4a#patient_race

https://demo.simplereport.gov/app/results/upload/submit/guide?facility=a8740505-f8c0-47e4-bd1b-e21d5dea3b4a#patient_ethnicity

dont map to the FHIR converter values.

[/backend/src/main/java/gov/cdc/usds/simplereport/db/model/PersonUtils.java#L663-L680](https://github.com/CDCgov/prime-simplereport/blob/7800350c5c91f8e3a95e6513bbdd6a5d6fa5c109/backend/src/main/java/gov/cdc/usds/simplereport/db/model/PersonUtils.java#L663-L680)
```java
  public static final Map<String, String> raceMap =
      Map.of(
          "native", "1002-5",
          "asian", "2028-9",
          "black", "2054-5",
          "pacific", "2076-8",
          "white", "2106-3",
          "other", "2131-1",
          "unknown", MappingConstants.UNK_CODE,
          "refused", MappingConstants.ASKED_BUT_UNKNOWN_CODE // Asked, but unknown
          );

  public static final Map<String, List<String>> ETHNICITY_MAP =
      Map.of(
          "hispanic", List.of("H", "Hispanic or Latino"),
          "not_hispanic", List.of("N", "Not Hispanic or Latino"),
          "refused", List.of("U", "unknown"));
```
 
### Proposed solution 
extend the PersonUtils to accept the values from the bulk uploader
extend the behavior in the bulkuploader to allow reverse mapping, from value to text

### PR DESCRIPTION
**Pull request by zdeveloper**
# BACKEND PULL REQUEST

## Related Issue

- resolves #6346
- support the race and ethnicity values from the bulk uploader

### CODE REVIEW

**Review by mpbrown — APPROVED** [review]
LGTM!

File: backend/src/main/java/gov/cdc/usds/simplereport/utils/BulkUploadResultsToFhir.java [hunk 1]
```diff
@@ -219,8 +220,8 @@ private Bundle convertRowToFhirBundle(TestResultRow row, UUID orgId) {
                 .dob(LocalDate.parse(row.getPatientDob().getValue(), DATE_TIME_FORMATTER))
                 .address(patientAddr)
                 .country(DEFAULT_COUNTRY)
-                .race(row.getPatientRace().getValue())
-                .ethnicity(row.getPatientEthnicity().getValue())
+                .race(getRaceLiteral(row.getPatientRace().getValue()))
+                .ethnicity(getEthnicityLiteral(row.getPatientEthnicity().getValue()))
```
Comment (DanielSass) [inline backend/src/main/java/gov/cdc/usds/simplereport/utils/BulkUploadResultsToFhir.java:224]: Does it make sense to use a different map here than the one we're using in the fhir converter?

The race map in the fhir converter is throwing me for a loop by having values that go both ways.
```
    raceMap.put("native", NATIVE_CODE);
    raceMap.put(NATIVE_CODE, "native");
```

If we're going to map the bulk upload accepted values to the single entry expected equivalent only to map it back to the loinc code (which could have been the bulk upload starting value) I think it makes sense for that first map to be in the bulk upload code and be explicit in what its doing.
