### PR TITLE
Finish account creation flow, frontend and backend

### LINKED ISSUE #1531: Voice Call MFA: Design & build the successful enroll UI
### Background
As part of the custom account creation work, UI flows need to be built for each MFA option (Okta Verify, SMS, voice call, Google Authenticator, FIDO2, and email.) This ticket is for the frontend work needed to enroll a voice call MFA.

For more information about MFA enrollment, see [this doc](https://docs.google.com/document/d/14Obz3uX8dP4wOMBE3G3HRqiw5us-mTBoOIZktZLgXrU/edit#heading=h.dsvfqfkcyvq7).
#### Design
Designs for the voice call enrollment have not been specified, but should be similar to SMS enrollment. 
The account creation designs are in [Figma](https://www.figma.com/file/NPSPM5SBzQ7Ra3mmr9M9cB/SimpleReport-Public-Site?node-id=1669%3A3).

#### Frontend Requirements
The frontend will need to make a request to the `POST \user-account\enroll-voice-call-mfa` endpoint when the user enters their phone number. This request should contain the phone number in the request body. If successful, this endpoint will initiate a phone call to the user with their activation code. If unsuccessful, the backend will return an error to the frontend that the phone number was misconfigured (see #1533 )

### LINKED ISSUE #1533: Voice Call MFA: Design & build the error enrollment UI
### Background
As part of the custom account creation work, UI flows need to be built for each MFA option (Okta Verify, SMS, voice call, Google Authenticator, FIDO2, and email.) This ticket is for the frontend work needed to handle errors while adding voice call MFA.

For more information about MFA enrollment, see [this doc](https://docs.google.com/document/d/14Obz3uX8dP4wOMBE3G3HRqiw5us-mTBoOIZktZLgXrU/edit#heading=h.dsvfqfkcyvq7).

### Proposed Solution

Designs for the voice call error state have not been specified, but again the flow should be very similar to SMS. 
The account creation designs are in [Figma](https://www.figma.com/file/NPSPM5SBzQ7Ra3mmr9M9cB/SimpleReport-Public-Site?node-id=1669%3A3).

The error to handle here is that the user entered an invalid phone number.

### LINKED ISSUE #1540: MFA Activation: Build successful passcode verification UI
### Background
Multiple MFA options require activation in the form of successful passcode entry after the user has enrolled in the MFA option. For SimpleReport, this applies to SMS, voice call, Okta Verify, and Google Authenticator. For these MFA options, Okta will send a text or call to the user-provided number at the end of a successful enrollment process, and the user is required to input that passcode to activate the MFA.

Note: This activation step is different from the usual passcode verification that’s done on login, and as such will need to be sent to a different API endpoint.

For further explanation of the activation process, see [this doc](https://docs.google.com/document/d/14Obz3uX8dP4wOMBE3G3HRqiw5us-mTBoOIZktZLgXrU/edit#heading=h.m9szttfnre8i).
### Proposed Solution
This ticket is for the frontend work required to build the success case for MFA activation with a passcode. This has been designed in [Figma](https://www.figma.com/file/NPSPM5SBzQ7Ra3mmr9M9cB/SimpleReport-Public-Site?node-id=1669%3A3).
The helper text for different SMS, voice call, Okta Verify, and Google Authenticator will need to be customized, but otherwise the forms should look the same.

The frontend will also need to send a request to the backend API endpoint to verify the activation passcode that the user input. This will take the form of a `POST` request to `\user-account\verify-activation-passcode`. The request should send the `passcode` to the backend, and expect either a successful response or an error message that the passcode was invalid.

### LINKED ISSUE #1541: MFA Activation: Design & build the error passcode verification UI
### Background
Multiple MFA options require activation in the form of successful passcode entry after the user has enrolled in the MFA option. For SimpleReport, this applies to SMS, voice call, Okta Verify, and Google Authenticator. For these MFA options, Okta will send a text or call to the user-provided number at the end of a successful enrollment process, and the user is required to input that passcode to activate the MFA.

Note: This activation step is different from the usual passcode verification that’s done on login, and as such will need to be sent to a different API endpoint.

For further explanation of the activation process, see [this doc](https://docs.google.com/document/d/14Obz3uX8dP4wOMBE3G3HRqiw5us-mTBoOIZktZLgXrU/edit#heading=h.m9szttfnre8i).

### Proposed Solution
This ticket is for the frontend work required to design and build the error case for MFA activation with a passcode. 

The error case to handle here is that the user entered an incorrect passcode. In that case, the user should be prompted to re-enter the passcode (but we don’t need to send them a new passcode unless they request it - see #1542 ). The re-entered passcode can be resent to the `\user-account\verify-activation-passcode` endpoint.

### LINKED ISSUE #1542: MFA Activation: Resend activation code
### Background
Multiple MFA options require activation in the form of successful passcode entry after the user has enrolled in the MFA option. For SimpleReport, this applies to SMS, voice call, Okta Verify, and Google Authenticator. For these MFA options, Okta will send a text or call to the user-provided number at the end of a successful enrollment process, and the user is required to input that passcode to activate the MFA.

Note: This activation step is different from the usual passcode verification that’s done on login, and as such will need to be sent to a different API endpoint.

For further explanation of the activation process, see [this doc](https://docs.google.com/document/d/14Obz3uX8dP4wOMBE3G3HRqiw5us-mTBoOIZktZLgXrU/edit#heading=h.m9szttfnre8i).

### Proposed Solution
This ticket is the frontend work required to resend the activation code if a user requests it. To do so, the frontend will need to send a request to the backend endpoint `POST \user-account\resend-activation-passcode`. This request body is empty; the backend will handle sending a new passcode through Okta.

### LINKED ISSUE #1543: Email MFA: Design & build a successful enrollment UI
### Background
As part of the custom account creation work, UI flows need to be built for each MFA option (Okta Verify, SMS, voice call, Google Authenticator, FIDO2, and email.) This ticket is for the frontend work to enroll email MFA.

For more information about MFA enrollment, see [this doc](https://docs.google.com/document/d/14Obz3uX8dP4wOMBE3G3HRqiw5us-mTBoOIZktZLgXrU/edit#heading=h.dsvfqfkcyvq7).

#### Design
Designs for the voice call enrollment have not been specified, but should be similar to other [MFA enrollment pages](https://www.figma.com/file/NPSPM5SBzQ7Ra3mmr9M9cB/SimpleReport-Public-Site?node-id=1669%3A3). 

Screen Shot 2021-05-07 at 5 03 52 PM

#### Frontend Requirements
The email enrollment page will need to make a request to the backend api endpoint `POST \user-account\enroll-email-mfa` with the user's email in the body of the request.

### LINKED ISSUE #1544: Email MFA: Design & build the error enrollment UI
### Background
As part of the custom account creation work, UI flows need to be built for each MFA option (Okta Verify, SMS, voice call, Google Authenticator, FIDO2, and email.) This ticket is for the frontend work needed to handle errors while adding email MFA.

For more information about MFA enrollment, see [this doc](https://docs.google.com/document/d/14Obz3uX8dP4wOMBE3G3HRqiw5us-mTBoOIZktZLgXrU/edit#heading=h.dsvfqfkcyvq7).

### Proposed Solution

Designs for the email error state have not been specified, but again the flow should be very similar to SMS. 
The account creation designs are in [Figma](https://www.figma.com/file/NPSPM5SBzQ7Ra3mmr9M9cB/SimpleReport-Public-Site?node-id=1669%3A3).

The error to handle here is that the user entered an invalid email address. In this case, we can request the user to re-enter the email, and send it to the same `POST \user-account\enroll-email-mfa` endpoint.

### LINKED ISSUE #1545: Okta Verify MFA: Build the enrollment page
### Background
As part of the custom account creation work, UI flows need to be built for each MFA option (Okta Verify, SMS, voice call, Google Authenticator, FIDO2, and email.) This ticket is for the frontend work to add Okta Verify enrollment.

For more information about MFA enrollment, see [this doc](https://docs.google.com/document/d/14Obz3uX8dP4wOMBE3G3HRqiw5us-mTBoOIZktZLgXrU/edit#heading=h.dsvfqfkcyvq7).

### Proposed Solution

To support Okta Verify as an MFA, we’ll need to display a unique QR code to the user that allows them to continue with enrollment in the Okta Verify app. The authentication enrollment designs are in [Figma](https://www.figma.com/file/NPSPM5SBzQ7Ra3mmr9M9cB/SimpleReport-Public-Site?node-id=1669%3A3).

To retrieve the QR code to display, the frontend will make a `GET` request to `\user-account\okta-verify-qr`. This request will return the QR code to display. The user will have to click continue to get to the verification page after they’ve enrolled on their device.
Note: since the backend flows for Okta and Google Authenticator are different (a QR code generated for one will not work for the other) different endpoints must be used. Otherwise, the pages are identical.

### LINKED ISSUE #1547: MFA: Add endpoint to verify passcode for all MFAs that require activation
### Background
For several MFA options (voice call, SMS, and authentication apps), there’s an additional activation step required before the MFA can be used. This activation verifies that the passcode sent to the user in the enrollment step was received and is correct. This ticket handles the creation of an endpoint to validate the activation passcode that was sent to the user.

For more information about activation, see [this doc](https://docs.google.com/document/d/14Obz3uX8dP4wOMBE3G3HRqiw5us-mTBoOIZktZLgXrU/edit#heading=h.m9szttfnre8i).

### Proposed Solution
In `UserAccountCreationController`, add the endpoint `POST \user-account\validate-activation-passcode`.
params:

- `passcode`
- `HTTPServletRequest`

The `stateToken` and `tokenId` will need to be extracted from the session stored in `HTTPServletRequest`. They should be stored as attributes under `stateToken` and `tokenId`, respectively.

In `OktaAuthentication`, add a method to handle passcode activation.
params:

- `stateToken`
- `factorId`
- `passcode`

In `LiveOktaAuthentication`, you’ll need to make an [`activateFactor`](https://developer.okta.com/okta-auth-java/apidocs/com/okta/authn/sdk/client/AuthenticationClient.html#activateFactor-java.lang.String-com.okta.authn.sdk.resource.ActivateFactorRequest-com.okta.authn.sdk.AuthenticationStateHandler-) call on the `AuthenticationClient`. This `activateFactor` call should use [`ActivatePassCodeFactorRequest`](https://developer.okta.com/okta-auth-java/apidocs/com/okta/authn/sdk/resource/ActivatePassCodeFactorRequest.html), which is where the passcode will be set.

Once the `activateFactor` call has been made, verify that it was successful by calling [`verifyActivation`](https://developer.okta.com/okta-auth-java/apidocs/com/okta/authn/sdk/client/AuthenticationClient.html#verifyActivation-java.lang.String-java.lang.String-com.okta.authn.sdk.AuthenticationStateHandler-) on the factor id and state id.

Extract the new state token from the [`AuthenticationResponse`](https://developer.okta.com/okta-auth-java/apidocs/com/okta/authn/sdk/resource/AuthenticationResponse.html) and return it to `UserAccountCreationController` to re-set on the session. (Note: this may not actually be necessary, but I can’t find documentation on whether the state token changes with each request or if it only changes state internally in Okta. This is safest though.)

Update `DemoOktaAuthentication` with a dummy method to validate activated factors.

### LINKED ISSUE #1548: MFA Activation: Add endpoint to resend activation factor
### Background
For several MFA options (voice call, SMS, and authentication apps), there’s an additional activation step required before the MFA can be used. This activation verifies that the passcode sent to the user in the enrollment step was received and is correct. For SMS and voice calls, we additionally need to give the user the opportunity to resend the text message or call containing the passcode. This ticket represents the backend work required to do so.

For more information about activation, see [this doc](https://docs.google.com/document/d/14Obz3uX8dP4wOMBE3G3HRqiw5us-mTBoOIZktZLgXrU/edit#heading=h.m9szttfnre8i).

### Proposed Solution
In `UserAccountCreationController`, add the endpoint `POST \user-account\resend-activation-passcode`. 
params:

- `HTTPServletRequest`

The `stateToken` and `factorId` will need to be extracted from the session stored in `HTTPServletRequest`. They should be stored as attributes under `stateToken` and `factorId`, respectively.

In `OktaAuthentication`, add a method to resend the activation code.
params:

- `stateToken`
- `factorId`

For `LiveOktaAuthentication`, you’ll need to make a [`resendActivationFactor`](https://developer.okta.com/okta-auth-java/apidocs/com/okta/authn/sdk/client/AuthenticationClient.html#resendActivateFactor-java.lang.String-java.lang.String-com.okta.authn.sdk.AuthenticationStateHandler-) request on the `AuthenticationClient`.  

You will also need to update `DemoOktaAuthentication` with a dummy method to resend the activation passcode.

### LINKED ISSUE #1559: Authenticator App MFA: Add API endpoint to enroll authenticator
### Background
As part of the custom account creation work, the backend needs to support enrolling each MFA option (Okta Verify, SMS, voice call, Google Authenticator, FIDO2, and email.) This ticket is for the backend work needed to initialize authenticator app MFAs (Google Authenticator and Okta Verify for now).

For more information about the backend requirements to enroll MFAs, see [this doc](https://docs.google.com/document/d/14Obz3uX8dP4wOMBE3G3HRqiw5us-mTBoOIZktZLgXrU/edit#heading=h.mfpwh65qjtxl).

### Proposed Solution
Unlike other MFA options, authentication apps require a unique QR code to be posted to the user so they can complete enrollment within the app. The Okta Authentication SDK also does not appear to support fetching these QR codes, as the MFA enrollment methods there do not return anything. Therefore, this API endpoint will need to use the [Okta User SDK](https://developer.okta.com/okta-sdk-java/apidocs/com/okta/sdk/resource/user/User.html) to retrieve the QR code.

In `UserAccountCreationController`, add the endpoint `GET \user-account\authenticator-qr`. 
params:
- `HTTPServletRequest`
- `String appType` (for now, `GOOGLE` or `OKTA`)

From the request, extract the `userId` stored as a session attribute. 

Add a `getAuthenticatorQR` method to `OktaAuthenticator`. 
params:
- `userId`
- `String appType`

First, you will need to add a new `Client` to `LiveOktaAuthenticator`. This `Client` will be the same kind that's used in [LiveOkaRepository](https://github.com/CDCgov/prime-simplereport/blob/ad65d2a0d1495b01dc95dd8319a334604c064fc1/backend/src/main/java/gov/cdc/usds/simplereport/idp/repository/LiveOktaRepository.java#L87). Using this `Client`, call the  [`getUser` method](https://developer.okta.com/okta-sdk-java/apidocs/com/okta/sdk/client/Client.html#getUser-java.lang.String-) with the provided `userId`.

Once you have the user object, call [`enrollFactor`](https://developer.okta.com/okta-sdk-java/apidocs/com/okta/sdk/resource/user/User.html#enrollFactor-com.okta.sdk.resource.user.factor.UserFactor-). The [`UserFactor`](https://developer.okta.com/okta-sdk-java/apidocs/com/okta/sdk/resource/user/factor/UserFactor.html) passed to that `enroll` method is both where we will set the MFA type and get the QR code. The [`FactorType`](https://developer.okta.com/okta-sdk-java/apidocs/com/okta/sdk/resource/user/factor/FactorType.html) is `TOKEN_SOFTWARE_TOTP`. The [`FactorProvider`](https://developer.okta.com/okta-sdk-java/apidocs/com/okta/sdk/resource/user/factor/FactorProvider.html) will depend on the `appType`, but will be one of `GOOGLE` or `OKTA`.

The `UserFactor` that is returned from `enrollFactor` has several key pieces of information. First, the `id` will need to be extracted and returned to `UserAccountCreationController` so that it may be stored in the session as a `factorId`. The QR code will also be in this `UserFactor`, as one of the `embedded` fields. - it also needs to be returned to `UserAccountCreationController` so that it can further be returned to the frontend. Finally, you must call the `activate` method for the factor to send a passcode to the user. 

The Okta API call to enroll Google Authenticator is [here](https://developer.okta.com/docs/reference/api/factors/#enroll-google-authenticator-factor); it provides helpful information about the shape of the response.

You will also need to update the `DemoOktaRepository` with a dummy method to send a QR code authentication apps.

### LINKED ISSUE #1663: Research Security Key MFA Enrollment
### Background

As part of the custom MFA enrollment work, we need to support users enrolling a security key. This is slightly more complex than other MFA enrollment options, because the frontend needs to be able to sense when the user touches the key.

### Details

It seems as though there are a couple different ways to enroll security keys as Okta factors. As best I can tell, we'll want to use the [U2F factor enrollment](https://developer.okta.com/docs/reference/api/factors/#enroll-u2f-factor) to get a `nonce` from Okta to enroll the key. This will require the frontend to use a U2F API, but Okta doesn't specify which to use.

The other factor enrollment option that seems tenable is the [`yubikey` factor enrollment](https://developer.okta.com/docs/reference/api/factors/#enroll-yubikey-factor), but I believe that one would require us to issue the yubikeys to users, since we'd need to verify the current passcode. Definitely worth investigating further, however.

The Okta Management SDK does seem to support enrolling a user in a U2F factor; see [U2fUserFactorProfile](https://developer.okta.com/okta-sdk-java/development/apidocs/com/okta/sdk/resource/user/factor/U2fUserFactorProfile.html).

### Summary

We need to figure out how to enroll security keys for Okta MFA. We'll need to figure out an API to use on the frontend for this, as well as determine which enrollment to use on the backend.

### PR DESCRIPTION
**Pull request by nickclyde**
## Related Issue or Background Info

Sorry for the extremely huge PR, but this is the only way @emmastephenson and I could finish everything off and work out all the kinks :weary: 

- Resolves #1559 
- Resolves #1548
- Resolves #1547
- Resolves #1663
- Resolves #1545
- Resolves #1544
- Resolves #1543
- Resolves #1542 
- Resolves #1531
- Resolves #1533
- Resolves #1541
- Resolves #1540

## Changes Proposed

- Finish all necessary backend changes needed to get all MFA options working:
  - Adds a TOTP generator dependency for testing Okta TOTP enrollment
  - Sets the `FACTOR_ID_KEY` attribute on the Spring Session in many endpoints to keep track of MFA enrollment in the session
  - Adds and implements necessary API endpoints for security key and TOTP enrollment and activation
  - Implements API endpoint for security code resending for SMS, Email, and Voice calll MFA
  - Adds `ActivateSecurityKeyRequest` class for security key activation endpoint
  - Adds all of the logic needed to interact with Okta SDKs and API endpoints to `LiveOktaAuthentication`, huge shoutout to @emmastephenson for this work!
  - Adds backend tests for Okta logic
- Finish all necessary frontend changes needed to get all MFA options working:
  - Update CSP to allow loading QR Code images from Okta
  - Add new endpoints to `AccountCreationApiService`
  - Alter `request` in `AccountCreationApiService` to support JSON responses as well as bare 200s
  - Add paths for and components for TOTP code verification pages
  - Adds page for security keys that implements WebAuthn standard
  - Add lots of UI tests for these components

## Additional Information

- Also added some nice transition loading cards between pages
- Added some REST mocks to the Storybook stories that needed them

## Screenshots / Demos

https://user-images.githubusercontent.com/9121162/121267332-e4799e00-c870-11eb-94f4-17f5eb75c059.mp4

https://user-images.githubusercontent.com/9121162/121267338-e6436180-c870-11eb-9725-75c8057ff130.mp4

https://user-images.githubusercontent.com/9121162/121267343-e9d6e880-c870-11eb-8e32-334323f5ea5e.mp4

https://user-images.githubusercontent.com/9121162/121267351-ec394280-c870-11eb-8141-6e4ce4173237.mp4

https://user-images.githubusercontent.com/9121162/121267355-ed6a6f80-c870-11eb-9971-792f09385218.mp4

https://user-images.githubusercontent.com/9121162/122260077-b6efae80-ce87-11eb-99f2-f7dfa7888acd.mp4

### Testing
This PR adds `LiveOktaAuthenticationTest`, which makes actual calls to Okta to send a user through the account creation process. The test is currently disabled until we can figure out how to run it infrequently (so as not to add too much burden on our Okta quota.)
The original backend PR [here](https://github.com/CDCgov/prime-simplereport/pull/1751) has a bit more information about the backend changes.

### UI
- [ ] Any changes to the UI/UX are approved by design 
- [ ] Any new or updated content (e.g. error messages) are approved by design 

### Testing
- [ ] Includes a summary of what a code reviewer should verify

### Changes are Backwards Compatible
- ~~[ ] Database changes are submitted as a separate PR~~
  - ~~[ ] Any new tables that do not contain PII are accompanied by a GRANT SELECT to the no-PHI user~~
  - ~~[ ] Any changes to tables that have custom no-PHI views are accompanied by changes to those views~~
- ~~[ ] GraphQL schema changes are backward compatible with older version of the front-end~~

### Security
- [ ] Changes with security implications have been approved by a security engineer (changes to  authentication, encryption, handling of PII, etc.)
- [ ] Any dependencies introduced have been vetted and discussed

## Cloud
- ~~[ ] DevOps team has been notified if PR requires ops support~~
- ~~[ ] If there are changes that cannot be tested locally, this has been deployed to our Azure `test` environment for verification~~

### CODE REVIEW

File: frontend/src/app/accountCreation/LoadingCard/LoadingCard.tsx [hunk 1]
```diff
@@ -0,0 +1,19 @@
+import { Card } from "../../commonComponents/Card/Card";
+import { CardBackground } from "../../commonComponents/CardBackground/CardBackground";
+import iconLoader from "../../../../node_modules/uswds/dist/img/loader.svg";
+
+interface Props {
+  message: string;
+}
+
+export const LoadingCard = (props: Props) => {
```
Comment (nickclyde) [inline frontend/src/app/accountCreation/LoadingCard/LoadingCard.tsx:9]: This component is used as a transition between pages, it gets rendered when `loading` is true on most components

File: frontend/src/app/accountCreation/MfaComplete/MfaComplete.tsx [hunk 2]
```diff
@@ -25,6 +25,7 @@ export const MfaComplete = () => {
           className="margin-top-3"
           label={"Get started"}
           type={"submit"}
+          onClick={() => (window.location.pathname = "/")}
```
Comment (nickclyde) [inline frontend/src/app/accountCreation/MfaComplete/MfaComplete.tsx:28]: For now, I just set the "Get started" button on the final page to redirect to the home page of the static site. Once we implement the in-app login flow, I will change this to redirect to `/login` or whatever we end up using

File: frontend/src/app/accountCreation/MfaEmailVerify/MfaEmailVerify.stories.tsx [hunk 3]
```diff
@@ -7,7 +7,7 @@ export default {
   component: MfaEmailVerify,
   argTypes: {},
   args: {
-    location: { state: { email: "foo@bar.com" } },
+    location: { state: { contact: "foo@bar.com" } },
```
Comment (nickclyde) [inline frontend/src/app/accountCreation/MfaEmailVerify/MfaEmailVerify.stories.tsx:10]: Changed this to `contact` since it is now using the generalized `MfaVerify` component

File: frontend/src/app/accountCreation/MfaGoogleAuth/MfaGoogleAuth.stories.tsx [hunk 4]
```diff
@@ -1,16 +1,19 @@
...
 
+import { getMocks } from "../../../stories/storyMocks";
+
 import { MfaGoogleAuth } from "./MfaGoogleAuth";
 
 export default {
   title: "App/Account set up/Step 3a: Google Authenticator MFA",
   component: MfaGoogleAuth,
+  parameters: {
+    msw: getMocks("enrollTotpMfa"),
```
Comment (nickclyde) [inline frontend/src/app/accountCreation/MfaGoogleAuth/MfaGoogleAuth.stories.tsx:11]: Added this mock so that this story will render with a QR code

File: frontend/src/app/accountCreation/MfaSecurityKey/MfaSecurityKey.tsx [hunk 5]
```diff
@@ -1,10 +1,56 @@
...
 import iconLoader from "../../../../node_modules/uswds/dist/img/loader.svg";
+import { AccountCreationApi } from "../AccountCreationApiService";
+import { strToBin, binToStr } from "../../utils/text";
 
 export const MfaSecurityKey = () => {
+  const [attestation, setAttestation] = useState("");
+  const [clientData, setClientData] = useState("");
+  const [activated, setActivated] = useState(false);
+
+  useEffect(() => {
```
Comment (nickclyde) [inline frontend/src/app/accountCreation/MfaSecurityKey/MfaSecurityKey.tsx:17]: This `useEffect` runs once after the component mounts

File: frontend/src/app/accountCreation/MfaTotp/MfaTotp.tsx [hunk 6]
```diff
@@ -1,15 +1,43 @@
...
 import { CardBackground } from "../../commonComponents/CardBackground/CardBackground";
 import Button from "../../commonComponents/Button/Button";
 import StepIndicator from "../../commonComponents/StepIndicator";
 import { accountCreationSteps } from "../../../config/constants";
+import iconLoader from "../../../../node_modules/uswds/dist/img/loader.svg";
+import { LoadingCard } from "../LoadingCard/LoadingCard";
 
 interface Props {
-  qrCode: string;
+  enrollFunction: Function;
```
Comment (nickclyde) [inline frontend/src/app/accountCreation/MfaTotp/MfaTotp.tsx:13]: Generalized this component to be used both for Google Auth and Okta Verify - the API enrollment function is passed through as a prop

File: frontend/src/app/accountCreation/MfaTotp/MfaTotp.tsx [hunk 7]
```diff
@@ -1,15 +1,43 @@
...
   totpType: string;
 }
 
 export const MfaTotp = (props: Props) => {
+  const [qrCode, setQrCode] = useState("");
+  const [submitted, setSubmitted] = useState(false);
+
+  useEffect(() => {
+    const getQrCode = async () => {
+      const { qrcode } = await props.enrollFunction();
```
Comment (nickclyde) [inline frontend/src/app/accountCreation/MfaTotp/MfaTotp.tsx:23]: This `useEffect` runs once on component load to enroll the factor and grab the link to the QR code from the backend

File: frontend/src/app/accountCreation/MfaTotp/MfaTotp.tsx [hunk 8]
```diff
@@ -1,15 +1,43 @@
...
+  }, [props]);
+
+  if (!qrCode) {
+    return <LoadingCard message="Retrieving QR code..." />;
+  }
+
+  if (submitted) {
+    return (
+      <Redirect
+        to={{ pathname: `${window.location.pathname.split("/uac")[1]}/verify` }}
```
Comment (nickclyde) [inline frontend/src/app/accountCreation/MfaTotp/MfaTotp.tsx:36]: This just redirects to the current path with `/verify` tacked on the end

File: frontend/src/app/accountCreation/MfaTotp/MfaTotp.tsx [hunk 9]
```diff
@@ -26,15 +54,22 @@ export const MfaTotp = (props: Props) => {
...
-          {props.qrCode ? (
+          {qrCode !== "" ? (
+            <img src={qrCode} alt="TOTP QR Code" className="height-card" />
+          ) : (
             <img
-              src={props.qrCode}
-              alt="TOTP QR Code"
-              className="height-card"
+              className="square-5 chromatic-ignore"
+              src={iconLoader}
```
Comment (nickclyde) [inline frontend/src/app/accountCreation/MfaTotp/MfaTotp.tsx:62]: Placeholder loading icon while retrieving the QR code link from the backend

File: frontend/src/app/accountCreation/MfaVerify/MfaVerify.tsx [hunk 10]
```diff
@@ -9,9 +9,11 @@ import StepIndicator from "../../commonComponents/StepIndicator";
 import { accountCreationSteps } from "../../../config/constants";
 import { AccountCreationApi } from "../AccountCreationApiService";
 import Alert from "../../commonComponents/Alert";
+import { LoadingCard } from "../LoadingCard/LoadingCard";
 
 interface Props {
   hint: ReactElement;
+  hideResend?: boolean;
```
Comment (nickclyde) [inline frontend/src/app/accountCreation/MfaVerify/MfaVerify.tsx:16]: This generalized component is used to verify the security code from all MFA options - but resend isn't needed for TOTP, so this prop hides it

File: frontend/src/app/commonComponents/Card/Card.tsx [hunk 11]
```diff
@@ -3,12 +3,14 @@ import siteLogo from "../../../img/simplereport-logo-color.svg";
 export type CardProps = {
   logo?: boolean;
   bodyKicker?: string;
+  bodyKickerCentered?: boolean;
```
Comment (nickclyde) [inline frontend/src/app/commonComponents/Card/Card.tsx:6]: Added this prop for the `LoadingCard` component so that the header is centered

**Review by maya — CHANGES_REQUESTED** [review]
Can you bring this up to date with `main`? The chromatic snapshots look like they aren't up-to-date.

Can you add the loading page as a story?

**Comment by nickclyde** [comment]
@maya done and done.

File: frontend/src/app/commonComponents/Card/Card.tsx [hunk 12]
```diff
@@ -22,7 +24,11 @@ export const Card: React.FC<CardProps> = ({
           <div className="border-bottom border-base-lighter margin-x-neg-3 margin-top-3"></div>
         </header>
       )}
-      {bodyKicker && (
+      {bodyKicker && bodyKickerCentered ? (
+        <div className="display-flex flex-column flex-align-center">
+          <p className="font-ui-sm text-bold margin-top-3">{bodyKicker}</p>
+        </div>
+      ) : (
         <p className="font-ui-sm text-bold margin-top-3">{bodyKicker}</p>
```
Comment (maya) [inline frontend/src/app/commonComponents/Card/Card.tsx:32]: This still needs the `bodyKicker` prop wrapped around this. Can you re-add? It's causing an unintended spacing shift.

**Review by maya — DISMISSED** [review]
One comment here to resolve the spacing issues. See comments in Chromatic for more.

File: frontend/src/app/commonComponents/Card/Card.tsx (hunk 12 above)
Comment (nickclyde) [reply frontend/src/app/commonComponents/Card/Card.tsx:32]: Fixed :thumbsup:

**Comment by nickclyde** [comment]
Not sure what happened with the UI changes, looks like the changes from #1659 didn't get merged in properly? Trying to sort that all out now

**Comment by maya** [comment]
Is this page from your walkthrough video in Storybook?

Screen Shot 2021-06-09 at 3 47 07 PM

I couldn't find it and only see the loading pages where I thought to find those.

**Comment by nickclyde** [comment]
Yeah, check out my comment in chromatic - that page loads fine in Storybook if you run locally, but it uses a mock like introduced by #1702, and I'm guessing our deployed storybook/chromatic that CI uses isn't configured right to support the mocks?

**Comment by nickclyde** [comment]
@maya I'm not sure how to fix the mock in Chromatic - might need to reach out to Nick S when he returns. In the meantime can you run storybook on this branch locally and confirm the pages in question look right and then approve in Chromatic?

**Comment by maya** [comment]
@nickclyde I also reached out to Chromatic and awaiting their response. Looks like @Rebecca-LM had one minor change request in Chromatic. Lmk if you can do that and I'll approve.

**Comment by maya** [comment]
@nickclyde all approved ✅ in chromatic!

**Comment by nickclyde** [comment]
@maya Thanks for reaching out to Chromatic! That led me in the right direction and I was able to fix the mocks, Google Auth and Okta Verify components are showing properly now :+1:

File: backend/src/main/java/gov/cdc/usds/simplereport/api/model/useraccountcreation/ActivateSecurityKeyRequest.java [hunk 13]
```diff
@@ -0,0 +1,15 @@
+package gov.cdc.usds.simplereport.api.model.useraccountcreation;
+
+import javax.validation.constraints.Size;
+import lombok.AllArgsConstructor;
+import lombok.Getter;
+
+@Getter
+@AllArgsConstructor
+public class ActivateSecurityKeyRequest {
+  @Size(max = RequestConstants.LARGE_REQUEST_STRING_LIMIT)
```
Comment (bmaden-usds) [inline backend/src/main/java/gov/cdc/usds/simplereport/api/model/useraccountcreation/ActivateSecurityKeyRequest.java:10]: I think these should be `@NotNull`, too.  Must have been in the last PR, but `EnrollMfaRequest` should also be `@NotNull`, right?

**Review by bmaden-usds — COMMENTED** [review]
I think we should be passing something other than `JSONObject` around since it seems too arbitrary.

The REST endpoints should be responding with `Content-Type: application/json` when they are sending a json body.  Changing JSONObject might fix this for free.

File: frontend/src/app/accountCreation/LoadingCard/LoadingCard.stories.tsx [hunk 14]
```diff
@@ -0,0 +1,19 @@
+import { Story, Meta } from "@storybook/react";
+
+import { LoadingCard } from "./LoadingCard";
+
+export default {
+  title: "App/Account set up/Loading card",
+  component: LoadingCard,
+  argTypes: {},
+  args: {
+    message: "Verifying security code ...",
```
Comment (maya) [inline frontend/src/app/accountCreation/LoadingCard/LoadingCard.stories.tsx:10]:
```suggestion
    message: "Verifying security code …",
```

Comment (maya) [reply frontend/src/app/accountCreation/LoadingCard/LoadingCard.stories.tsx:10]: Changing from 3 periods to `&hellip;` - should this be in the component rather than added to each use of the component since they all use the same pattern?

**Review by maya — CHANGES_REQUESTED** [review]
One small change

File: frontend/src/app/accountCreation/MfaSelect/MfaSelect.test.tsx [hunk 15]
```diff
@@ -3,13 +3,27 @@ import { MemoryRouter, Route, Switch } from "react-router";
...
 import { MfaSecurityKey } from "../MfaSecurityKey/MfaSecurityKey";
 import { MfaSms } from "../MfaSms/MfaSms";
 
 import { MfaSelect } from "./MfaSelect";
 
+jest.mock("../AccountCreationApiService", () => ({
+  AccountCreationApi: {
+    enrollTotpMfa: (app: string) => {
+      return new Promise((res, rej) => {
+        if (app === "Google" || app === "Okta") {
```
Comment (nickscialli-usds) [inline frontend/src/app/accountCreation/MfaSelect/MfaSelect.test.tsx:17]: Can `app` be a string union or enum rather than a string?

File: frontend/src/app/accountCreation/MfaTotp/MfaTotp.tsx (hunk 6 above)
Comment (nickscialli-usds) [reply frontend/src/app/accountCreation/MfaTotp/MfaTotp.tsx:13]: Based on its use below, it seems like this could be typed as `() => Promise<{ qrcode: string }>`

File: frontend/src/app/accountCreation/MfaTotp/MfaTotp.tsx [hunk 16]
```diff
@@ -1,15 +1,43 @@
...
+  const [qrCode, setQrCode] = useState("");
+  const [submitted, setSubmitted] = useState(false);
+
+  useEffect(() => {
+    const getQrCode = async () => {
+      const { qrcode } = await props.enrollFunction();
+      setQrCode(qrcode);
+    };
+    getQrCode();
+  }, [props]);
```
Comment (nickscialli-usds) [inline frontend/src/app/accountCreation/MfaTotp/MfaTotp.tsx:27]: this dependency array could just be `[props.enrollFunction]`

File: frontend/src/app/accountCreation/MfaTotp/MfaTotp.tsx [hunk 17]
```diff
@@ -26,15 +54,22 @@ export const MfaTotp = (props: Props) => {
           app.
         </p>
         <div className="display-flex flex-column flex-align-center">
-          {props.qrCode ? (
+          {qrCode !== "" ? (
```
Comment (nickscialli-usds) [inline frontend/src/app/accountCreation/MfaTotp/MfaTotp.tsx:57]: Isn't `qrCode` guaranteed to exist at this point because we returned early in line 29? https://github.com/CDCgov/prime-simplereport/pull/1817/files#diff-212d61abf5384f41aff05b423eae28c1dfb1d97edece165deb1322078c5ab20bR29

**Review by nickscialli-usds — COMMENTED** [review]
Really cool feature set! Left some comments for the front-end parts.

File: frontend/src/app/accountCreation/LoadingCard/LoadingCard.tsx [hunk 18]
```diff
@@ -0,0 +1,19 @@
...
+  return (
+    <CardBackground>
+      <Card logo bodyKicker={props.message} bodyKickerCentered={true}>
+        <div className="display-flex flex-column flex-align-center">
+          <img className="square-5 chromatic-ignore" src={iconLoader} alt="" />
```
[the remark this answers is not in the document]
Comment (maya) [reply frontend/src/app/accountCreation/LoadingCard/LoadingCard.tsx:14]: An empty alt tag is correct b/c the loading information is already given in the card's message.

File: backend/src/main/java/gov/cdc/usds/simplereport/api/apiuser/UserAccountCreationController.java [hunk 19]
```diff
@@ -107,22 +107,20 @@ public void enrollVoiceCallMfa(
...
+   * Enrolls a user in email MFA, using the account email address stored in Okta.
    *
-   * @param requestBody contains the user-provided email address.
    * @param request contains session information about the user, including their Okta id.
    * @throws OktaAuthenticationFailureException if the provided email address is invalid.
    */
   @PostMapping("/enroll-email-mfa")
-  public void enrollEmailMfa(@RequestBody EnrollMfaRequest requestBody, HttpServletRequest request)
-      throws OktaAuthenticationFailureException {
+  public void enrollEmailMfa(HttpServletRequest request) throws OktaAuthenticationFailureException {
```
[the remark this answers is not in the document]
Comment (emmastephenson) [reply backend/src/main/java/gov/cdc/usds/simplereport/api/apiuser/UserAccountCreationController.java:120]: Ah yes, this is something we uncovered in testing - if the email address doesn't match the email on file with Okta, then Okta throws a pretty incomprehensible error. @nickclyde, could you remove the form on the frontend asking for the user email?

File: backend/src/main/java/gov/cdc/usds/simplereport/idp/authentication/LiveOktaAuthentication.java [hunk 20]
```diff
@@ -177,30 +219,224 @@ public String enrollVoiceCallMfa(String userId, String phoneNumber)
...
+   *
+   * <p>https://developer.okta.com/docs/reference/api/factors/#response-example-12
+   *
+   * @param userId the user id of the user making the enrollment request.
+   * @param appType the appType of the app being enrolled (for now, one of Okta Verify or Google
+   *     Authenticator.)
+   * @throws OktaAuthenticationFailureException if the app type is not recognized, Okta fails to
+   *     enroll the MFA option, or the result from Okta does not contain a QR code.
+   */
+  public JSONObject enrollAuthenticatorAppMfa(String userId, String appType)
```
[the remark this answers is not in the document]
Comment (emmastephenson) [reply backend/src/main/java/gov/cdc/usds/simplereport/idp/authentication/LiveOktaAuthentication.java:263]: I'm changing this one to FactorAndQrCode, which is just a POJO with the factor and qr code. 

For the enrollSecurityKey request, I know @nickclyde had formatted the frontend so that it pretty much just accepted the activation JS object from Okta (following [this guide](https://developer.okta.com/docs/reference/api/factors/#get-registration-information-from-webauthn-authenticator-by-calling-the-webauthn-javascript-api)). So I could change the response type to a Java object that just has all the required information, but I don't know how difficult that would be to unwrap on the frontend.

File: backend/src/main/java/gov/cdc/usds/simplereport/api/model/useraccountcreation/ActivateSecurityKeyRequest.java (hunk 13 above)
Comment (emmastephenson) [reply backend/src/main/java/gov/cdc/usds/simplereport/api/model/useraccountcreation/ActivateSecurityKeyRequest.java:10]: Good catch, pretty much all of these request formatters should be `@NotNull` 😄  Updating now.

File: backend/src/main/java/gov/cdc/usds/simplereport/api/apiuser/UserAccountCreationController.java (hunk 19 above)
[the remark this answers is not in the document]
Comment (nickclyde) [reply backend/src/main/java/gov/cdc/usds/simplereport/api/apiuser/UserAccountCreationController.java:121]: Yes I totally forgot about this, will update!

File: frontend/src/app/accountCreation/LoadingCard/LoadingCard.stories.tsx (hunk 14 above)
Comment (nickclyde) [reply frontend/src/app/accountCreation/LoadingCard/LoadingCard.stories.tsx:10]: Yeah good idea, I can def move it into the component

File: frontend/src/app/accountCreation/MfaSecurityKey/MfaSecurityKey.tsx [hunk 21]
```diff
@@ -1,10 +1,57 @@
...
+    const enrollKey = async () => {
+      const { activation } = await AccountCreationApi.enrollSecurityKeyMfa();
+      if (!activation.challenge) return;
+      const publicKey = Object.assign({}, activation);
+      // Convert activation object's challenge and user id from string to binary
+      publicKey.challenge = strToBin(activation.challenge);
+      publicKey.user.id = strToBin(activation.user.id);
+
+      // navigator.credentials is a global object on WebAuthn-supported clients, used to access WebAuthn API
```
[the remark this answers is not in the document]
Comment (nickclyde) [reply frontend/src/app/accountCreation/MfaSecurityKey/MfaSecurityKey.tsx:26]: We actually tried implementing the older U2F spec but ran into a lot of issues with it. In the interest of getting this feature out I might suggest that we just tell the user they need to update their browser if they want to use their security key with SR? Maybe render a card with something to that effecn and a back button if `navigator.credentials` isn't defined?

File: frontend/src/app/accountCreation/MfaTotp/MfaTotp.tsx (hunk 17 above)
Comment (nickclyde) [reply frontend/src/app/accountCreation/MfaTotp/MfaTotp.tsx:57]: Yeah good catch! I wrote this before I implemented the `LoadingCard` component. Will fix

File: frontend/src/app/accountCreation/LoadingCard/LoadingCard.tsx (hunk 18 above)
[the remark this answers is not in the document]
Comment (nickclyde) [reply frontend/src/app/accountCreation/LoadingCard/LoadingCard.tsx:14]: Hmm, doesn't the alt tag refer to the content of the image though, rather than the card's message? Should the alt be something like `loading spinner`?

[the remark this answers is not in the document]
Comment (maya) [reply frontend/src/app/accountCreation/LoadingCard/LoadingCard.tsx:14]: Yes, it refers to the image. But it's illustrative of the existing text "Verifying security code ..." just above. It can be a bit of a judgment call wrt empty alt text, but the existing text seems sufficient.

File: frontend/src/app/accountCreation/LoadingCard/LoadingCard.stories.tsx (hunk 14 above)
Comment (nickclyde) [reply frontend/src/app/accountCreation/LoadingCard/LoadingCard.stories.tsx]: Fixed in 5993c15

File: frontend/src/app/accountCreation/AccountCreationApiService.ts [hunk 22]
```diff
@@ -18,13 +18,16 @@ const getOptions = (
...
-    if (!res.ok) {
-      throw res;
-    }
+const request = async (path: string, body: any) => {
+  const res = await fetch(API_URL + path, getOptions(body));
+  if (!res.ok) {
+    throw res;
+  }
+  try {
+    return await res.json();
```
[the remark this answers is not in the document]
Comment (nickclyde) [reply frontend/src/app/accountCreation/AccountCreationApiService.ts]: Fixed in 58d5434

File: frontend/src/app/accountCreation/MfaSecurityKey/MfaSecurityKey.tsx (hunk 21 above)
[the remark this answers is not in the document]
Comment (nickclyde) [reply frontend/src/app/accountCreation/MfaSecurityKey/MfaSecurityKey.tsx:27]: Added in 2968655

File: frontend/src/app/accountCreation/MfaSelect/MfaSelect.test.tsx (hunk 15 above)
Comment (nickclyde) [reply frontend/src/app/accountCreation/MfaSelect/MfaSelect.test.tsx:17]: Fixed in b732210

File: frontend/src/app/accountCreation/MfaTotp/MfaTotp.tsx (hunk 6 above)
Comment (nickclyde) [reply frontend/src/app/accountCreation/MfaTotp/MfaTotp.tsx]: Fixed in c7c755e

File: frontend/src/app/accountCreation/MfaTotp/MfaTotp.tsx (hunk 16 above)
Comment (nickclyde) [reply frontend/src/app/accountCreation/MfaTotp/MfaTotp.tsx]: Fixed in c7c755e

File: frontend/src/app/accountCreation/MfaTotp/MfaTotp.tsx (hunk 17 above)
Comment (nickclyde) [reply frontend/src/app/accountCreation/MfaTotp/MfaTotp.tsx]: Fixed in c7c755e

File: backend/src/main/java/gov/cdc/usds/simplereport/api/apiuser/UserAccountCreationController.java (hunk 19 above)
[the remark this answers is not in the document]
Comment (nickclyde) [reply backend/src/main/java/gov/cdc/usds/simplereport/api/apiuser/UserAccountCreationController.java:121]: Fixed in 95f668e

**Comment by nickclyde** [comment]
Here is the new flow for email MFA after removing the email input cc @bmaden-usds 

https://user-images.githubusercontent.com/9121162/122259734-4fd1fa00-ce87-11eb-87fd-bfb3586de3dc.mp4

**Review by nickscialli-usds — APPROVED** [review]
Good with the resolution of my comments 👍

File: backend/build.gradle [hunk 23]
```diff
@@ -16,6 +16,7 @@ sourceCompatibility = '11'
 
 ext {
     kickstartVersion = '11.0.0'
+    set('springCloudVersion', "Hoxton.SR6")
```
Comment (benwarfield-usds) [inline backend/build.gradle:19]: Should we just set these in gradle.properties instead?

File: backend/build.gradle [hunk 24]
```diff
@@ -82,13 +83,25 @@ dependencies {
     testImplementation 'org.springframework.security:spring-security-test'
     testImplementation 'com.yannbriancon:spring-hibernate-query-utils:1.0.3'
 
+    // used to autoconfigure WireMock for testing
+    testImplementation 'org.springframework.cloud:spring-cloud-contract-wiremock'
+	testImplementation 'org.springframework.cloud:spring-cloud-starter-contract-stub-runner'
```
Comment (benwarfield-usds) [inline backend/build.gradle:88]:
```suggestion
    testImplementation 'org.springframework.cloud:spring-cloud-contract-wiremock'
    testImplementation 'org.springframework.cloud:spring-cloud-starter-contract-stub-runner'
```

File: backend/build.gradle [hunk 25]
```diff
@@ -98,6 +111,7 @@ springBoot {
 test {
     // people sometimes export this to run local dev more easily: don't let it break the tests
     environment "SPRING_PROFILES_ACTIVE", ""
+    environment "OKTA_TESTING_DISABLEHTTPSCHECK", "true"
```
Comment (benwarfield-usds) [inline backend/build.gradle:114]: Is this a Spring-managed property in the `okta.testing` namespace? If so, could/should it be in the `application-default.yaml` properties file?

File: backend/gradle/dependency-locks/runtimeClasspath.lockfile [hunk 26]
```diff
@@ -4,10 +4,10 @@
 antlr:antlr:2.7.7
 ch.qos.logback:logback-classic:1.2.3
 ch.qos.logback:logback-core:1.2.3
-com.azure:azure-core-http-netty:1.9.0
-com.azure:azure-core:1.14.1
-com.azure:azure-storage-common:12.11.0-beta.2
-com.azure:azure-storage-queue:12.9.0-beta.2
+com.azure:azure-core-http-netty:1.7.1
```
Comment (benwarfield-usds) [inline backend/gradle/dependency-locks/runtimeClasspath.lockfile:7]: This seems bad?

File: backend/gradle/dependency-locks/compileClasspath.lockfile [hunk 27]
```diff
@@ -21,10 +21,15 @@ com.fasterxml.jackson.module:jackson-module-parameter-names:2.11.3
 com.fasterxml.woodstox:woodstox-core:6.2.1
 com.fasterxml:classmate:1.5.1
 com.github.stephenc.jcip:jcip-annotations:1.0-1
-com.google.code.findbugs:jsr305:1.3.9
+com.google.code.findbugs:jsr305:3.0.2
 com.google.code.gson:gson:2.8.6
-com.google.http-client:google-http-client-jackson2:1.21.0
-com.google.http-client:google-http-client:1.21.0
+com.google.errorprone:error_prone_annotations:2.3.4
```
Comment (benwarfield-usds) [inline backend/gradle/dependency-locks/compileClasspath.lockfile:26]: I'm confused at the changes to our compile and runtime classpath locks, if there are no changes to our `implementation` dependencies.

File: backend/src/main/java/gov/cdc/usds/simplereport/api/apiuser/UserAccountCreationController.java [hunk 28]
```diff
@@ -27,14 +29,13 @@
...
+  private static final String FACTOR_ID_KEY = "factorId";
 
   @Autowired private OktaAuthentication _oktaAuth;
 
   @PostConstruct
   private void init() {
-    LOG.info(
-        "WIP: User account request creation REST endpoint enabled. Not for use in production at this time.");
+    LOG.info("User account request creation REST endpoint enabled.");
   }
```
Comment (benwarfield-usds) [inline backend/src/main/java/gov/cdc/usds/simplereport/api/apiuser/UserAccountCreationController.java:39]: This can be deleted, there's no toggle or profile on it anyway.

**Review by benwarfield-usds — CHANGES_REQUESTED** [review]
I'm confused and worried by the dependency changes, so I'm going to throw a flag on those right now, then keep reading.

**Comment by emmastephenson** [comment]
> I'm confused and worried by the dependency changes, so I'm going to throw a flag on those right now, then keep reading.

That's my bad, I ran `refresh-dependencies` at some point when I was trying to get the spring-wiremock installation to work. Reverting those files to `main` now.

File: backend/build.gradle (hunk 25 above)
Comment (nickclyde) [reply backend/build.gradle:114]: For some reason, applying it there doesn't work. The only way we could get this to apply properly is through env variables ¯\_(ツ)_/¯

Comment (benwarfield-usds) [reply backend/build.gradle:114]: That's wild. I have some guesses as to how that could be the case, but they probably wouldn't change much. (Also I'm not 100% sure what this is doing, but it looks like a reasonable thing based on what it says.)

I guess it's possible that putting it in `application.yaml` would do it if I'm right, but it's not clear that there's a benefit to that.

Come to that, though, it would probably be good to have some comment on one of the places this is being done explaining what it does. 😁

Comment (nickclyde) [reply backend/build.gradle:114]: Will add a comment, but basically this makes the Okta client not complain/ throw exceptions when we use a non-https wiremock server as our org url!

File: backend/gradle/dependency-locks/runtimeClasspath.lockfile (hunk 26 above)
Comment (nickclyde) [reply backend/gradle/dependency-locks/runtimeClasspath.lockfile:7]: Seems to have happened as a result of needing to use the `spring-cloud-dependencies` BOM to get the wiremock annotations to work properly, [see here](https://cloud.spring.io/spring-cloud-contract/1.1.x/single/spring-cloud-contract.html#_spring_cloud_contract_wiremock)
image
@emmastephenson and I are trying to find a way around this, downgrading our azure deps is not desirable!

File: backend/build.gradle (hunk 25 above)
Comment (nickclyde) [reply backend/build.gradle:124]: Added!

File: backend/gradle/dependency-locks/runtimeClasspath.lockfile (hunk 26 above)
Comment (nickclyde) [reply backend/gradle/dependency-locks/runtimeClasspath.lockfile]: Fixed this by updating `spring-cloud-dependencies` to `2020.0.3` and by forcing resolution of the runtime azure deps. Lockfiles are unchanged from `main` now

Comment (nickclyde) [reply backend/gradle/dependency-locks/runtimeClasspath.lockfile]: Scratch that - it turns out `2020.0.3` breaks the test we are using WireMock in. Reverting to `Hoxton.SR11` along with some more forced resolutions results in a change set that only upgrades or adds dependencies, and the test passes.

**Review by bmaden-usds — APPROVED** [review]
Changes to the email workflow and most of the responses look good.  I still think the content-type of `/enroll-security-key-mfa` should be fixed, but don't want to hold this up on it.

File: backend/src/main/java/gov/cdc/usds/simplereport/api/apiuser/UserAccountCreationController.java [hunk 29]
```diff
@@ -133,9 +132,52 @@ public void enrollEmailMfa(@RequestBody EnrollMfaRequest requestBody, HttpServle
...
+   * @throws OktaAuthenticationFailureException if the user is not recognized or Okta cannot enroll
+   *     their security key.
+   */
+  @PostMapping("/enroll-security-key-mfa")
+  public String enrollSecurityKeyMfa(HttpServletRequest request)
+      throws OktaAuthenticationFailureException {
+    String userId = getUserId(request.getSession());
+    JSONObject enrollResponse = _oktaAuth.enrollSecurityKey(userId);
+    request.getSession().setAttribute(FACTOR_ID_KEY, enrollResponse.getString(FACTOR_ID_KEY));
+    return new JSONObject(enrollResponse, "activation").toString();
```
[the remark this answers is not in the document]
Comment (emmastephenson) [reply backend/src/main/java/gov/cdc/usds/simplereport/api/apiuser/UserAccountCreationController.java:164]: I think we're going to push this off to a followup PR if that's alright, since we'd like to get this out ASAP so we can begin user testing. But I'll flag it with a TODO and follow up with a PR by the end of the week!

File: backend/src/main/java/gov/cdc/usds/simplereport/api/apiuser/UserAccountCreationController.java [hunk 30]
```diff
@@ -133,9 +132,54 @@ public void enrollEmailMfa(@RequestBody EnrollMfaRequest requestBody, HttpServle
...
+  /**
+   * Enrolls a security key for the user, returning data needed to finish activation.
+   *
+   * @param request contains session information about the user, including their Okta id.
+   * @return activation object with information to finish enrolling the security key, including a
+   *     challenge and user id.
+   * @throws OktaAuthenticationFailureException if the user is not recognized or Okta cannot enroll
+   *     their security key.
+   */
+  @PostMapping("/enroll-security-key-mfa")
```
Comment (benwarfield-usds) [inline backend/src/main/java/gov/cdc/usds/simplereport/api/apiuser/UserAccountCreationController.java:155]: General nitpick: the URLs are reasonably self-explanatory, but it seems like it could be made more structured, and I would argue that it would be good if they were. So

* `/mfa/enroll/security-key`
* `/mfa/activate/security-key`
* `/mfa/enroll/totp`
* `/mfa/activate` (for all the ones that just require returning a code and you don't care which type of factor it is)

This would also enable having a handler for `/mfa/enroll/{type}` that dispatched on the type instead of having a different handler method for each type of MFA, but that might be an unnecessary luxury. 😄

File: backend/src/main/java/gov/cdc/usds/simplereport/idp/authentication/LiveOktaAuthentication.java [hunk 31]
```diff
@@ -8,43 +8,71 @@
...
+  @Autowired
   public LiveOktaAuthentication(OktaClientProperties oktaClientProperties) {
+    initialize(oktaClientProperties.getOrgUrl(), oktaClientProperties.getToken());
+  }
+
+  public LiveOktaAuthentication(String orgUrl, String token) {
+    initialize(orgUrl, token);
+  }
+
+  private void initialize(String orgUrl, String token) {
```
Comment (benwarfield-usds) [inline backend/src/main/java/gov/cdc/usds/simplereport/idp/authentication/LiveOktaAuthentication.java:67]:
```suggestion
```

**Review by benwarfield-usds — COMMENTED** [review]
If you have time to read only one or two of this somewhat scattershot array of comments on the Java side, please choose:
* general concerns expressed at the top of the controller, specifically with respect to session attribute clean-up and being able to use this with an already-logged-in user
* easy package organization fix expressed on `OktaAuthentication`

File: backend/src/main/java/gov/cdc/usds/simplereport/api/apiuser/UserAccountCreationController.java [hunk 32]
```diff
@@ -107,22 +108,20 @@ public void enrollVoiceCallMfa(
       throws OktaAuthenticationFailureException {
     String userId = getUserId(request.getSession());
     String factorId = _oktaAuth.enrollVoiceCallMfa(userId, requestBody.getUserInput());
-    request.getSession().setAttribute(FACTOR_ID, factorId);
+    request.getSession().setAttribute(FACTOR_ID_KEY, factorId);
```
[the remark this answers is not in the document]
Comment (emmastephenson) [reply backend/src/main/java/gov/cdc/usds/simplereport/api/apiuser/UserAccountCreationController.java:111]: I don't think factors have been verified to persist in the spring-session table, but user ids have been verified, and I don't think there'd be any differences? Since they're being set the same way.
