### PR TITLE
Fix test result submit button bug

### LINKED ISSUE #1229: Bug: Submit button disabled until user re-enters test questionnaire
Bug reported by user: "When going to submit test results, the "submit" button is not clickable and we have to reenter the test questionnaire information in order for it to submit (uncheck and recheck the symptoms responses, then hit Continue). This has happened about 5-10 times out of the 45 tests we've done."

More info:
- User is using Chrome on Macbooks.
- Heather and Alicia may have observed the same bug during Florida onsite - in that case, the user had to refresh the page in order to enable the Submit button.
- We have not been able to replicate this bug.

### PR DESCRIPTION
**Pull request by nickscialli-usds**
## Related Issue or Background Info

- Fixes #1229

## Changes Proposed

- Rather than using our own `isSubmitting` state (which was being set too early in the flow!), just use the `loading` prop returned by `useMutation` since that will definitely be correct
- Remove some hacky disable logic on the submit button in favor of setting `pointerEvent` to `"none"` in the CSS exit transition

### CODE REVIEW

File: frontend/src/app/testQueue/QueueItem.tsx [hunk 1]
```diff
@@ -300,8 +298,6 @@ const QueueItem: any = ({
 
   const [removePatientId, setRemovePatientId] = useState<string>();
 
-  let forceSubmit = false;
```
Comment (nickscialli-usds) [inline frontend/src/app/testQueue/QueueItem.tsx:303]: This was odd to find and could explain some unpredictable/hard to replicate behavior

File: frontend/src/app/testQueue/QueueItem.tsx [hunk 2]
```diff
@@ -316,11 +312,8 @@ const QueueItem: any = ({
     showNotification(toast, alert);
   };
 
-  const onTestResultSubmit = (e?: React.MouseEvent<HTMLButtonElement>) => {
-    setIsSubmitting(true);
```
Comment (nickscialli-usds) [inline frontend/src/app/testQueue/QueueItem.tsx:320]: I think this was probably the real issue: the `isSubmitting` state variable is redundant with `loading` from `useMutation` and is clearly set to `true` too early here.

**Review by nullflux — APPROVED** [review]

**Review by nathancrtr — APPROVED** [review]
LGTM 🌮
