### PR TITLE
[BUG] Update bulk uploader datetime validations

### LINKED ISSUE #8253: [BUG] Update bulk uploader datetime validations
### Description

- Discovered while working on #8225
- The results bulk uploader [date time validation](https://github.com/CDCgov/prime-simplereport/blob/26b324f9f2348ca64b4eb398782eaf4269103c2a/backend/src/main/java/gov/cdc/usds/simplereport/validators/CsvValidatorUtils.java#L100) can be updated to address the following scenarios:
   - extra whitespace (e.g. "10/18/2024 10:00" - passes but with extra whitespaces it fails)
   - Verify that the documentation makes the intended format clear.   
   - preceding whitespace in date time string causes a DateTimeParseException to get thrown inside the CompletableFuture returned by TestResultUploadService#submitResultsToCovidPipeline -> this should show an error to the user
   
### Steps to reproduce
[Steps here](https://github.com/CDCgov/prime-simplereport/pull/8225#issuecomment-2445401198)
- use the csv in the comment above

### Proposed Solution

The frontend will already show an error toast if backend doesn't respond with a 200, so we could make sure to throw 
 a **specific error message** to handle exceptions in any case where:

data fails to parse or get transformed before we send to ReportStream due to trailing white space or white space between the dates. Some examples of when we should throw an error: 

```
"01 / 01 / 2023 11 : 11"
"01/01/2023 11:11 EST  "
" 01/01/2023 11:11 EST "
```

#### Additional Context

please be wary of overlap work on which is meant to throw a generic error message: 
[https://app.zenhub.com/workspaces/simplereport-2025-and-onwards-605b43a6ceb92c000f86279a/issues/gh/cdcgov/prime-simplereport/8496](url)

### PR DESCRIPTION
**Pull request by kevinfiol**
# BACKEND PULL REQUEST

## Related Issue

Resolves #8253

## Changes Proposed

- Removes the use of REGEX to validate date time strings in CSV upload. We now attempt to parse the date string, and catch any errors.

## Additional Information

- ~~Error messaging for `validateDateTimeZoneCode` has been modified to be more clear to the user~~
- Use of `convertToZonedDateTime` to attempt parsing of the date string

## Testing

You can use this .csv to start, which should fail by default with an invalid timezone for the `specimen_collection_date` column.

[pr_ordering_INVALID_TIMEZONE.csv](https://github.com/user-attachments/files/19571496/pr_ordering_INVALID_TIMEZONE.csv)

You can modify this column to test the other scenarios.

Should fail:
```
01 / 01 / 2023 11 : 11
01/01 /2023 11:11 EST
01/01/2023 11:11 WAT
```

Should pass:
```
    01/01/2023 11:11 EST   
01/01 /2023 11:11
```

### CODE REVIEW

File: backend/src/main/java/gov/cdc/usds/simplereport/validators/CsvValidatorUtils.java [hunk 1]
```diff
@@ -448,12 +447,30 @@ public static List<FeedbackMessage> validateDateFormat(ValueOrError input) {
...
+
+      if (hasTimezoneSubstring(value)) {
+        errors.addAll(validateDateTimeZoneCode(input));
+      }
+    } catch (Exception e) {
+      errors.add(
+          FeedbackMessage.builder()
+              .scope(ITEM_SCOPE)
+              .fieldHeader(input.getHeader())
+              .message(getInvalidValueErrorMessage(input.getValue(), input.getHeader()))
```
Comment (kevinfiol) [inline backend/src/main/java/gov/cdc/usds/simplereport/validators/CsvValidatorUtils.java:468]: I had originally modified the error messages to be more helpful to end users, but looks like several of our backend tests explicitly checks for the generic error message text (see: [TestErrorMessageUtil.java](https://github.com/CDCgov/prime-simplereport/blob/main/backend/src/test/java/gov/cdc/usds/simplereport/test_util/TestErrorMessageUtil.java)). I also am not sure if the copy is something we should run by product/design. Thoughts? :thinking:

Comment (emyl3) [reply backend/src/main/java/gov/cdc/usds/simplereport/validators/CsvValidatorUtils.java:470]: I'm thinking it's ok to leave as-is for now and maybe we can come back to it if we get more support messages/feedback from users saying it is confusing? 👀

**Review by emyl3 — DISMISSED** [review]
Tested locally! Nice fix, Kevin! Thank you! 🤩

File: backend/src/main/java/gov/cdc/usds/simplereport/validators/CsvValidatorUtils.java [hunk 2]
```diff
@@ -448,12 +449,30 @@ public static List<FeedbackMessage> validateDateFormat(ValueOrError input) {
...
+      convertToZonedDateTime(value);
+
+      if (hasTimezoneSubstring(value)) {
+        errors.addAll(validateDateTimeZoneCode(input));
+      }
+    } catch (DateTimeParseException | StringIndexOutOfBoundsException e) {
+      errors.add(
+          FeedbackMessage.builder()
+              .scope(ITEM_SCOPE)
+              .fieldHeader(input.getHeader())
```
Comment (mehansen) [inline backend/src/main/java/gov/cdc/usds/simplereport/validators/CsvValidatorUtils.java:469]:
```suggestion
              .fieldHeader(input.getHeader())
              .source(ResultUploadErrorSource.SIMPLE_REPORT)
```

I think we want the source set to SR to indicate that this error is coming from our validation step in the [Result Upload Error](https://www.simplereport.gov/metabase/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjoyLCJ0eXBlIjoicXVlcnkiLCJxdWVyeSI6eyJzb3VyY2UtdGFibGUiOjUxfX0sImRpc3BsYXkiOiJ0YWJsZSIsInZpc3VhbGl6YXRpb25fc2V0dGluZ3MiOnt9fQ==) table

sorry if we're setting it somewhere else and I missed it

Comment (kevinfiol) [reply backend/src/main/java/gov/cdc/usds/simplereport/validators/CsvValidatorUtils.java:469]: Thanks @mehansen ; I've committed this suggestion.

**Review by mehansen — APPROVED** [review]
thank you!

File: backend/src/main/java/gov/cdc/usds/simplereport/validators/CsvValidatorUtils.java [hunk 3]
```diff
@@ -448,12 +449,31 @@ public static List<FeedbackMessage> validateDateFormat(ValueOrError input) {
...
-    List<FeedbackMessage> errors = new ArrayList<>(validateRegex(input, DATE_TIME_REGEX));
-    if (input.getValue() != null
-        && errors.isEmpty()
-        && input.getValue().matches(TIMEZONE_SUFFIX_REGEX)) {
-      errors.addAll(validateDateTimeZoneCode(input));
+    String value = parseString(input.getValue());
+    List<FeedbackMessage> errors = new ArrayList<>();
+
+    if (value == null) {
+      return errors;
```
Comment (DanielSass) [inline backend/src/main/java/gov/cdc/usds/simplereport/validators/CsvValidatorUtils.java:456]: I appreciate that with this update the fact that we're potentially passing back an empty error array is visible.  I don't think that's what I would have expected based on 

```java
List<FeedbackMessage> errors = new ArrayList<>(validateRegex(input, DATE_TIME_REGEX));
```

**Review by DanielSass — APPROVED** [review]
this is great, ty!
