### PR TITLE
Fix override date being clobbered on server return

### LINKED ISSUE #439: User can't type in override date year
Currently we are saving all data to the server and update the front-end based on what the server has. In the case of the test date override this is too slow and the user's subsequent typing is clobbered by the server value.

### PR DESCRIPTION
**Pull request by dmethvin-gov**
## Related Issue or Background Info

Fixes #439.

I discovered this while refactoring the forms stuff but wanted to fix it sooner without having to rush through that big set of changes.

## Changes Proposed

- Save the override date locally
- Only save to the server when the date is valid
- Incomplete dates won't be saved, if the user navigates away it will return to the old value

Ultimately I think we'll need to re-plumb the app something like described in #304 but this fixes the problem, mostly, for now. There are still situations where the user's typing might be clobbered but I think they'll be much less likely.

### CODE REVIEW

File: frontend/src/app/commonComponents/Dropdown.tsx [hunk 1]
```diff
@@ -14,7 +14,7 @@ interface Props {
   options: Option[];
   label?: string;
   name?: string;
-  onChange: (e: React.FormEvent<HTMLSelectElement>) => void;
+  onChange: (e: React.ChangeEvent<HTMLSelectElement>) => void;
```
Comment (dmethvin-gov) [inline frontend/src/app/commonComponents/Dropdown.tsx:17]: This was just fixing the type of the event handler, it's also in the big PR but I figured I should pull it over.

**Review by timothybest-usds — APPROVED** [review]

File: frontend/src/app/testQueue/QueueItem.tsx [hunk 2]
```diff
@@ -304,23 +304,30 @@ const QueueItem: any = ({
...
-    });
+  const onDateTestedChange = (e: React.ChangeEvent<HTMLInputElement>) => {
+    const dateTested = e.target.value;
+    // If we try to round-trip the date to the server, it is too slow and the
+    // new prop clobbers what the user typed after the request continued.
+    // So, only save complete recent dates but always update locally.
+    // This will need further fixing once we go to subscriptions, ugh.
+    updateDateTested(dateTested);
+    const thisYear = new Date().getFullYear();
+    const check = new RegExp(`^(${thisYear - 1}|${thisYear})-\\d\\d-\\d\\d`);
```
Comment (dmethvin-gov) [inline frontend/src/app/testQueue/QueueItem.tsx:324]: The `<input type="date" ... />` here always renders its date in `yyyy-mm-dd` format but displays it in localized format. I'm only treating the current and previous year as valid to reduce the chances of a minor typo updating the server with a bad date. I'm assuming we don't want to let people go crazy with back or forward dating but this is only checking the year. Once we get real form field validation we can narrow the date range (e.g. only back a month) and style the input to make it clear the data isn't good so we can warn before submit.
