### PR TITLE
Show new or updated facilities in the header dropdown and facilities

### LINKED ISSUE #2828: [BUG] Newly added facility doesn't show up without refreshing the page
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Newly added facility doesn't show up without refreshing the page

### Steps To Reproduce

- Add a facility
- Observe that the new facility doesn't show up when you save

### Expected Behavior

Newly added facility should show up without refreshing the page

### Additional context

https://user-images.githubusercontent.com/4952042/138180648-ff674c71-69b9-4c2b-8572-81590611f78e.mp4

### Does this issue have a priority label?

- [X] I have added a priority label

### Has issue been assigned to a team?

- [X] I have added a team label

### PR DESCRIPTION
**Pull request by alismx**
## Related Issue or Background Info

- Resolves #2828

## Changes Proposed

- Add or Update facilities in the store after saving.
- Do not cache Facilities on the manage facilities page

## Additional Information

- It may make sense to create a single unified way of supporting our access and utilization of facility data.
- Possibly extracting out queries to allow and encourage reuse.

### UI
- [ ] Any changes to the UI/UX are approved by design 
- [ ] Any new or updated content (e.g. error messages) are approved by design 

### Testing
- [ ] Includes a summary of what a code reviewer should verify

### Changes are Backwards Compatible
- [ ] Database changes are submitted as a separate PR
  - [ ] Any new tables that do not contain PII are accompanied by a GRANT SELECT to the no-PHI user
  - [ ] Any changes to tables that have custom no-PHI views are accompanied by changes to those views
        (including re-granting permission to the no-PHI user if need be)
  - [ ] Liquibase rollback has been tested locally using `./gradlew liquibaseRollbackSQL` or `liquibaseRollback`
  - [ ] Each new changeset has a corresponding [tag](https://docs.liquibase.com/change-types/community/tag-database.html)
- [ ] GraphQL schema changes are backward compatible with older version of the front-end

### Security
- [ ] Changes with security implications have been approved by a security engineer (changes to  authentication, encryption, handling of PII, etc.)
- [ ] Any dependencies introduced have been vetted and discussed

## Cloud
- [ ] DevOps team has been notified if PR requires ops support
- [ ] If there are changes that cannot be tested locally, this has been deployed to our Azure `test`, `dev`, or `pentest` environment for verification

### CODE REVIEW

File: frontend/src/app/Settings/Facility/ManageFacilitiesContainer.tsx [hunk 1]
```diff
@@ -1,76 +1,34 @@
...
-    }
-  }
-`;
-
 const ManageFacilitiesContainer: any = () => {
-  const { data, loading, error } = useQuery<SettingsData, {}>(GET_FACILITIES);
+  const { data, loading, error } = useGetManagedFacilitiesQuery({
+    fetchPolicy: "no-cache",
+  });
+  const setttingsData = data as SettingsData;
```
Comment (nathancrtr) [inline frontend/src/app/Settings/Facility/ManageFacilitiesContainer.tsx:9]: Typo: `setttings` -> `settings`

File: frontend/src/app/Settings/Facility/FacilityFormContainer.tsx [hunk 2]
```diff
@@ -225,6 +229,7 @@ const FacilityFormContainer: any = (props: Props) => {
     if (appInsights) {
       appInsights.trackEvent({ name: "Save Settings" });
     }
+    setUpdatedFacility(() => facility);
     const provider = facility.orderingProvider;
     const saveFacility = props.facilityId ? updateFacility : addFacility;
     await saveFacility({
```
Comment (nathancrtr) [inline frontend/src/app/Settings/Facility/FacilityFormContainer.tsx:235]: We will need to save created facilities in the Redux store _with_ their primary key IDs generated by the database. What I think this will look like is:

1. Updating the `addFacility`/`updateFacility` mutations to return `Facility` and its necessary subfields (including `internalId`)
2. Save the resolved value of the `saveFacility` call in `FacilityFormContainer.tsx` to a variable
3. Write that variable to local state as `updatedFacility`, and dispatch _that_ piece of state to the store

Comment (nathancrtr) [reply frontend/src/app/Settings/Facility/FacilityFormContainer.tsx]: **Note:** resolved in 0102220

**Review by nathancrtr — APPROVED** [review]
LGTM! 🎉 thanks for the thorough test coverage
