### PR TITLE
Johanna/5859 remove search button in search bar

### LINKED ISSUE #5859: Search button does nothing
## Area or Component

Device code lookup > Search button
Conduct Test > Search button

## Quick Summary

Clicking the button does nothing

## Accessibility Violation

[Role is incorrect](https://docs.deque.com/issue-help/1.0.0/en/aria-role-missing) 
https://cdc-devtools.dequecloud.com/issues/0c87f67d-8b8a-4da2-9278-3049c9687de4

## Action Requested

Remove the search button or provide it an action
If there are other places on the site where we have a search button that does nothing, see what's happening there and let's try to have same (accessible) behavior across the whole site

## Screenshots (optional)

https://github.com/CDCgov/prime-simplereport/assets/10108172/00253b70-5ab3-414d-bee1-13bb2c6fe094

## Source Code (optional)

https://github.com/CDCgov/prime-simplereport/blob/17c28123b9674ffbe4eef6b47ebcdf960d32d87e/frontend/src/app/uploads/DeviceLookup/DeviceLookup.tsx#L124-L130
https://github.com/CDCgov/prime-simplereport/blob/17c28123b9674ffbe4eef6b47ebcdf960d32d87e/frontend/src/app/testQueue/addToQueue/AddToQueueSearch.tsx#L266-L272

### PR DESCRIPTION
**Pull request by johanna-skylight**
# FRONTEND PULL REQUEST

## Related Issue

- Resolves #5859

## Changes Proposed

- Set the prop that hides the search button in the search input for the conduct test and device lookup pages.
- Add alia live prop to the search results of those two pages so the results get announced by the screen reader

## Additional Information
Some unit testing clean up also was done to the related unit testing files.

## Testing
This ticket is small but if someone needs to test the search functionality in the conduct test and device lookup pages the code is available in Dev5.

### CODE REVIEW

File: frontend/src/app/commonComponents/FormGroup.tsx [hunk 1]
```diff
@@ -1,19 +1,24 @@
...
-    <fieldset className="usa-fieldset">
-      <legend className="prime-formgroup-heading usa-legend">
-        {props.title}
-      </legend>
-      {props.children}
-    </fieldset>
-  </form>
-);
+const FormGroup = (props: FormGroupProps) => {
+  const WappringEl = props.asSectionGroup ? "div" : "form";
```
Comment (BobanL) [inline frontend/src/app/commonComponents/FormGroup.tsx:10]: I think this is a typo? Should it be `WrappingEl` instead?

**Review by BobanL — APPROVED** [review]
Changes look good!

File: frontend/src/app/commonComponents/FormGroup.tsx (hunk 1 above)
Comment (johanna-skylight) [reply frontend/src/app/commonComponents/FormGroup.tsx:10]: omg yes! thanks for catching this :D

**Review by fzhao99 — APPROVED** [review]

**Review by BobanL — APPROVED** [review]
