### PR TITLE
Fix accessibility issues in EmailTestResultModal

### LINKED ISSUE #4088: List of emails on the results email modal isn't a real list
## Area or Component
Results page - email modal ("Email results")

## Quick Summary
The list of emails is not coded properly as a list of items.

## Accessibility Violation
Visual list is not marked up as list: https://cdc-devtools.dequecloud.com/rule-help/en/semantic-list

## Action Requested
Change the DOM to include a real list for emails in the modal.

## Screenshots (optional)
Screen Shot 2022-07-26 at 4 37 17 PM

## Original Deque Issue
https://docs.google.com/spreadsheets/d/1b6xjubAN5Uw11DV4_B5zvSu7HeDI6Z-DpV4DMcToqAY/edit#gid=1978534823&range=33:33

### LINKED ISSUE #4090: Email results modal has wrong header
## Area or Component
Result page - "Email results" modal

## Quick Summary
The heading of the modal ("Email results") is coded as a `<header>` element, when it should really be an `h1`.

## Accessibility Violation
Visual heading text is not marked as heading: https://cdc-devtools.dequecloud.com/rule-help/en/semantic-heading

## Action Requested
Change the modal header to an `<h1>` element.
There are already multiple `<header>` tags on the main page, so it seems improper to add one just for the modal.

## Screenshots (optional)
Screen Shot 2022-07-27 at 12 15 16 PM

## Original Deque Issue
https://docs.google.com/spreadsheets/d/1b6xjubAN5Uw11DV4_B5zvSu7HeDI6Z-DpV4DMcToqAY/edit#gid=1978534823&range=32:32

### PR DESCRIPTION
**Pull request by emyl3**
# FRONTEND PULL REQUEST

## Related Issue
Resolves #4088 
Resolves #4090 

## Changes Proposed
- Display emails in the EmailTest Result modal as a `<li>`
- Change previous <div> with `header` class into a `<h1>`

## Additional Information
N/A

## Testing
- Make sure emails are displayed in a list element in the EmailTestResultModal
- Make sure header of that modal is now an `<h1>`
- Make sure styles have not changed too much 😅  ([see note about one style change here](https://github.com/CDCgov/prime-simplereport/pull/4338/files#r983621429))

## Screenshots / Demos
**Previous:**
Screen Shot 2022-09-29 at 09 14 35

**New**:
Screen Shot 2022-09-29 at 09 16 08

### CODE REVIEW

File: frontend/src/app/testResults/EmailTestResultModal.tsx [hunk 1]
```diff
@@ -45,9 +47,13 @@ export const EmailTestResultModal = ({ closeModal, testResultId }: Props) => {
               {formatFullName(patient)}'s test result from{" "}
               {formatDateLong(dateTested)} will be sent to the following emails:
             </div>
-            {patient.emails?.map((email: string) => (
-              <div key={email}>{email}</div>
-            ))}
+            <ul className="usa-list usa-list--unstyled">
+              {patient.emails?.map((email: string) => (
+                <li className="line-height-sans-2" key={email}>
```
Comment (emyl3) [inline frontend/src/app/testResults/EmailTestResultModal.tsx:52]: ⚠️ Chose to use a uswds provided class for the line height that was close to the original code as possible instead of adding a custom css class to make the line heights identical. (The difference is 0.8px -- new is 19.2px while the old is 18.4px -- which I feel is negligible for the benefit of not adding a custom css class)

**Review by fzhao99 — APPROVED** [review]

**Review by DanielSass — APPROVED** [review]

**Review by BobanL — APPROVED** [review]
