### PR TITLE
Certain backend errors no longer cause requests to not be logged in the audit log

### LINKED ISSUE #1779: Certain backend errors cause requests to not be logged in the audit log
### Description
When debugging the `datetime` issues we noticed that some of the errors being raised were not writing to the Audit log. This also caused an error where the `/graphql` endpoint would return a `400` instead of a `200`

### Steps to reproduce

1. go to the graphql playground
2. submit a `AddPatientToQueue` mutation with the value `05/14/2021` for `symptomOnset`
3. the API returns a 400 and no items are recorded in the audit log

### Expected behavior
The failed mutation `AddPatientToQueue` is recorded in the audit log and the API returns a `200` with the `CoercingParseValueException` in the response errors

### Additional context
[End-to-end transaction details](https://portal.azure.com/#blade/AppInsightsExtension/DetailsV2Blade/ComponentId/%7B%22SubscriptionId%22%3A%227d1e3999-6577-4cd5-b296-f518e5c8e677%22%2C%22ResourceGroup%22%3A%22prime-simple-report-prod%22%2C%22Name%22%3A%22prime-simple-report-prod-insights%22%2C%22LinkedApplicationType%22%3A0%2C%22ResourceId%22%3A%22%252Fsubscriptions%252F7d1e3999-6577-4cd5-b296-f518e5c8e677%252FresourceGroups%252Fprime-simple-report-prod%252Fproviders%252FMicrosoft.Insights%252Fcomponents%252Fprime-simple-report-prod-insights%22%2C%22ResourceType%22%3A%22microsoft.insights%252Fcomponents%22%2C%22IsAzureFirst%22%3Afalse%7D/DataModel/%7B%22eventId%22%3A%22d87d6d7b-be4d-11eb-8dfa-7f6b3776e47d%22%2C%22timestamp%22%3A%222021-05-26T18%3A11%3A47.424Z%22%2C%22cacheId%22%3A%22fb623b6f-759e-4096-afaf-4059d721b7f3%22%2C%22eventTable%22%3A%22requests%22%7D)
```
Caused by: java.lang.NullPointerException
...
	at gov.cdc.usds.simplereport.logging.AuditLoggingInstrumentation$ExecutionResultContext.onCompleted(AuditLoggingInstrumentation.java:86)
	at gov.cdc.usds.simplereport.logging.AuditLoggingInstrumentation$ExecutionResultContext.onCompleted(AuditLoggingInstrumentation.java:66)
```

### PR DESCRIPTION
**Pull request by nathancrtr**
## Related Issue or Background Info

Closes #1779 

## Changes Proposed
- Add a null-check in `AuditLoggingInstrumentation.java` so the request is logged in the audit log

## Additional Information
- The ticket states that the expected behavior of a result of this patch includes a `200` response from the API in the event of an `CoercingParseValueException`.
- Discussed with @nullflux - our feeling is that keeping the response as a `400` is sufficient at this time. While the `200` may be more technically correct, a `400` response does accurately indicate the nature of the error (i.e. "your request was bad, change something and try again").
- This decision was made with an eye towards velocity but if a reviewer feels strongly that we should undertake the work to send a `200` response please comment below

## Screenshots / Demos
Screen Shot 2021-06-29 at 2 10 53 PM

## Checklist for Author and Reviewer
- [ ] Is keeping the response code as a `400` for this case acceptable?

### UI
- [x] ~Any changes to the UI/UX are approved by design~
- [x] ~Any new or updated content (e.g. error messages) are approved by design~

### Testing
- [ ] Includes a summary of what a code reviewer should verify

### Changes are Backwards Compatible
- [x] ~Database changes are submitted as a separate PR~
  - [x] ~Any new tables that do not contain PII are accompanied by a GRANT SELECT to the no-PHI user~
  - [x] ~Any changes to tables that have custom no-PHI views are accompanied by changes to those views~
        ~(including re-granting permission to the no-PHI user if need be)~
  - [x] ~Liquibase rollback has been tested locally using `./gradlew liquibaseRollbackSQL` or `liquibaseRollback`~
- [x] ~GraphQL schema changes are backward compatible with older version of the front-end~

### Security
- [x] ~Changes with security implications have been approved by a security engineer (changes to  authentication, encryption, handling of PII, etc.)~
- [x] ~Any dependencies introduced have been vetted and discussed~

## Cloud
- [x] ~DevOps team has been notified if PR requires ops support~
- [x] ~If there are changes that cannot be tested locally, this has been deployed to our Azure `test` environment for verification~

### CODE REVIEW

File: backend/src/main/java/gov/cdc/usds/simplereport/logging/AuditLoggingInstrumentation.java [hunk 1]
```diff
@@ -80,7 +79,7 @@ public void onCompleted(ExecutionResult result, Throwable t) {
       LOG.trace("End of execution, audit entry being saved.");
       List<String> errorPaths =
           result.getErrors().stream()
-              .map(GraphQLError::getPath)
+              .map(e -> e.getPath() == null ? new ArrayList<Object>() : e.getPath())
```
Comment (nullflux) [inline backend/src/main/java/gov/cdc/usds/simplereport/logging/AuditLoggingInstrumentation.java:82]: **question (non-blocking):** Does `Collections.emptyList()` not work here?

Comment (nathancrtr) [reply backend/src/main/java/gov/cdc/usds/simplereport/logging/AuditLoggingInstrumentation.java]: It didn't... because `Collections` wasn't imported 🙂 Reverted in 37aeffc because it's a little more readable.

**Review by nickscialli-usds — APPROVED** [review]
