### PR TITLE
Fix status in upload list table

### LINKED ISSUE #3874: Fetch updated statuses for bulk upload
After users upload a CSV file, the status can either be "failure" or "pending".  We need to fetch the updated statuses for "pending" uploads and update the screen to inform the user.

Technical details:
- consider having a cron job that runs every _ minutes 

Questions:
- Can we ask report stream to publish status updates as it becomes available?

Screenshot from 2022-06-08 13-39-37

### PR DESCRIPTION
**Pull request by mehansen**
# FRONTEND PULL REQUEST

## Related Issue

Resolves #3874 

## Changes Proposed

- change status on the upload submission list page to reflect the http status of the submission instead of the overall status, to achieve parity with the behavior of the list view page in ReportStream

## Additional Information

- originally we thought we'd need to retrieve updated overall status (I am going to call this delivery status) of a submission from the RS API to keep our data in sync with RS, but turns out the status column on the list view page reflects the http status in the response (I've been calling this submission status), which just tells us whether the file was successfully submitted or not and presumably does not change
- RS's list view page filters out upload submissions with httpStatus != 200 or 201, we only save responses to our table if the overallStatus in the response != "Error", and the overallStatus = "Error" if httpStatus != 200 or 201. therefore getting all responses from our table for an org should achieve the same behavior as in the current RS list view
    - assumption is overallStatus = "Error" iff httpStatus != 200 or 201 based on [this thread](https://skylight-hq.slack.com/archives/C03A23UMGTS/p1655835850384329)

## Testing

- Check that upload submissions list view only has Status of "Success"
- Upload a valid file using the uploader and verify it appears in the list view with status immediately showing as "Success" instead of "Pending"
 
## Screenshots / Demos

capture

### Design
- [ ] Any UI/UX changes have a designer as a reviewer, and changes have been approved
- [ ] Any large-scale changes have been deployed to `test`, `dev`, or `pentest` and smoke-tested by both the engineering and design teams

### Content
- [ ] Any content changes have been approved by content team

### Support
- [ ] Any changes that might generate new support requests have been flagged to the support team
- [ ] Any changes to support infrastructure have been demo'd to support team

### Security
- [ ] Changes with security implications have been approved by a security engineer (changes to  authentication, encryption, handling of PII, etc.)
- [ ] Any dependencies introduced have been vetted and discussed

### CODE REVIEW

File: frontend/src/app/testResults/submissions/Submissions.tsx [hunk 1]
```diff
@@ -148,7 +148,7 @@ const Submissions = () => {
                     <th scope="col">Report ID</th>
                     <th scope="col">Date/Time submitted</th>
                     <th scope="col">Records</th>
-                    <th scope="col">Status</th>
+                    <th scope="col">Submission Status</th>
```
Comment (mehansen) [inline frontend/src/app/testResults/submissions/Submissions.tsx:151]: can I get feedback on this change? It's not exactly the same as in RS, but if we intend to eventually show Delivery Status (overallStatus) to users, it would be helpful to start differentiating between different types of status now so it's less confusing later. I propose using Submission Status and Delivery Status but am open to suggestions

Comment (nathancrtr) [reply frontend/src/app/testResults/submissions/Submissions.tsx]: @vz3 I believe you were out for our various "what is a 'status'" conversations with ReportStream. Meredith described the issue well in the notes for this PR, but just to reiterate: ReportStream tracks a "submission" or "overall" status that simply indicates whether the submission was initially accepted or rejected at the time of upload. They also have the notion of a "delivery status", which tracks the status of the results as they are processed and make their way to the respective PHDs.

Long-term, the "delivery status" seems by far the more useful of the two measures to track and display to users. However, even ReportStream itself does not currently display this information in its UI. Therefore, for the initial release, our status displayed to the user will be the "overall" status.

The questions here and beyond are: do we want to make any effort at communicating this difference to users at this stage? How do we want to prepare for the eventual inclusion of a "delivery status" given these competing notions?

Comment (nathancrtr) [reply frontend/src/app/testResults/submissions/Submissions.tsx]: We changed our minds 🙂 

Screen Shot 2022-06-30 at 4 57 18 PM

We will just drop the `Status` column for now and re-introduce when we can show more useful delivery information.
