### PR TITLE
Test results may be delivered to all patient phone numbers

### LINKED ISSUE #1949: In the Time of Test modal ask users to text all mobile numbers or no mobile numbers
### Description
Spec: https://docs.google.com/document/d/1Vk42CMKEtrFKqBbdPiz6JJ_uzB_RCsabqH2uFmwfPZE/edit#

String: "Would you like to receive your results via text message?"

If a text message fails, show which number(s) have failed in the error message.

### Proposed solution 

- [ ] In the time of test modal, update the question text to asks users if they would like to text all or none of the mobile numbers.  

- [ ] Display all of the numbers that will receive the text message

- [ ] Save text message settings as the default for the next test

- [ ] Text multiple phone numbers if there are multiple mobile numbers

- [ ] Update error message for failed text messages

### Additional context
Think through is the new alert about invalid phone numbers getting texted.

### PR DESCRIPTION
**Pull request by nathancrtr**
## Related Issue or Background Info

Closes #1949 

## Changes Proposed

* SMS service method to text patient links loops over all patient phone numbers
    * At this time, even a single failure will cause the server to respond with a `deliverySuccess` of `false`. We will update the error handling and the alert displayed to users on the frontend in a future ticket
* AOE modal lists all patient phone numbers when users specify that they would like to receive their results by text

## Additional Information

* Add `SmsDeliveryResult` model to represent a patient link delivery attempt
* Did some DRYing out of frontend type definitions for patients returned from `GetPatientsByFacility` query

## Screenshots / Demos
**Multiple phone numbers - all valid**

https://user-images.githubusercontent.com/27730981/127014502-459083a5-bbf5-45cc-8aef-9f3d5abbf97e.mov

**Multiple phone numbers - one or more invalid**

https://user-images.githubusercontent.com/27730981/127014544-1e967b7a-ad6b-4359-9faa-64c9413e17f0.mov

**No mobile phone numbers:**
Screen Shot 2021-07-28 at 11 38 26 AM

### UI
- [x] Any changes to the UI/UX are approved by design 
- [x] Any new or updated content (e.g. error messages) are approved by design 

### Testing
- [x] Includes a summary of what a code reviewer should verify

### Changes are Backwards Compatible
- [x] ~Database changes are submitted as a separate PR~
  - [x] ~Any new tables that do not contain PII are accompanied by a GRANT SELECT to the no-PHI user~
  - [x] ~Any changes to tables that have custom no-PHI views are accompanied by changes to those views~
        ~(including re-granting permission to the no-PHI user if need be)~
  - [x] ~Liquibase rollback has been tested locally using `./gradlew liquibaseRollbackSQL` or `liquibaseRollback`~
- [x] ~GraphQL schema changes are backward compatible with older version of the front-end~

### Security
- [x] ~Changes with security implications have been approved by a security engineer (changes to  authentication, encryption, handling of PII, etc.)~
- [x] ~Any dependencies introduced have been vetted and discussed~

## Cloud
- [x] ~DevOps team has been notified if PR requires ops support~
- [x] ~If there are changes that cannot be tested locally, this has been deployed to our Azure `test` environment for verification~

### CODE REVIEW

File: backend/src/main/java/gov/cdc/usds/simplereport/service/sms/SmsService.java [hunk 1]
```diff
@@ -46,17 +49,46 @@ void init() throws NumberParseException {
...
 
-  private String sendToPerson(Person p, String text) throws NumberParseException {
-    String msgId = sms.send(new PhoneNumber(formatNumber(p.getTelephone())), fromNumber, text);
-    LOG.debug("SMS send initiated {}", msgId);
-    return msgId;
+  private List<SmsDeliveryResult> sendToPerson(Person p, String text) {
+    List<SmsDeliveryResult> smsSendResults = new ArrayList<>();
+
+    p.getPhoneNumbers().stream()
+        .forEach(
```
Comment (nullflux) [inline backend/src/main/java/gov/cdc/usds/simplereport/service/sms/SmsService.java:73]: **question:** Since we're `.stream().forEach()`'ing here to add items to a List, might it make more sense to `map()` and then `.collect()` them directly into that stream?

File: backend/src/test/java/gov/cdc/usds/simplereport/service/sms/SmsServiceTest.java [hunk 2]
```diff
@@ -150,4 +166,53 @@ void sendPatientLinkSmsUpdatesPatientLinkExpiry() throws NumberParseException {
...
+    assertEquals(1, sut.size());
+    var result = sut.get(0);
+    assertEquals(_person.getPrimaryPhone().getNumber(), result.getTelephone());
+    assertEquals("some-twilio-id-10", result.getMessageId());
+    assertEquals(true, result.getDeliverySuccess());
+  }
+
+  @Test
+  @WithSimpleReportStandardAllFacilitiesUser
+  void sendPatientLinkSms_sendsToAllPatientPhoneNumbers() throws NumberParseException {
```
Comment (nullflux) [inline backend/src/test/java/gov/cdc/usds/simplereport/service/sms/SmsServiceTest.java:193]: **praise:** Thanks for covering the N=2 case!

File: frontend/src/app/testQueue/QueueItem.tsx [hunk 3]
```diff
@@ -174,14 +174,7 @@ if (process.env.NODE_ENV !== "test") {
...
   internalId: string;
-  patient: {
-    internalId: string;
-    firstName: string;
-    middleName: string;
-    lastName: string;
-    telephone: string;
-    birthDate: string;
-  };
+  patient: TestQueuePerson;
```
Comment (nullflux) [inline frontend/src/app/testQueue/QueueItem.tsx:177]: **praise:** Thanks for DRYing this out

File: frontend/src/app/testQueue/addToQueue/AddToQueueSearch.tsx [hunk 4]
```diff
@@ -48,6 +48,10 @@ export const QUERY_PATIENT = gql`
       birthDate
       gender
       telephone
+      phoneNumbers {
```
Comment (nullflux) [inline frontend/src/app/testQueue/addToQueue/AddToQueueSearch.tsx:51]: **question:** Does this introduce an N+1 query?

**Review by nullflux — APPROVED** [review]
Provisionally approved pending two Q's!

File: backend/src/main/java/gov/cdc/usds/simplereport/service/model/SmsDeliveryResult.java [hunk 5]
```diff
@@ -0,0 +1,26 @@
+package gov.cdc.usds.simplereport.service.model;
+
+public class SmsDeliveryResult {
+  private String telephone;
+  private String messageId;
+  private Boolean deliverySuccess;
```
Comment (nickscialli-usds) [inline backend/src/main/java/gov/cdc/usds/simplereport/service/model/SmsDeliveryResult.java:6]: **nitpick (non-blocking):** I think this can just be the `boolean` primitive type

File: backend/src/main/java/gov/cdc/usds/simplereport/service/model/SmsDeliveryResult.java [hunk 6]
```diff
@@ -0,0 +1,26 @@
+package gov.cdc.usds.simplereport.service.model;
+
+public class SmsDeliveryResult {
```
Comment (nickscialli-usds) [inline backend/src/main/java/gov/cdc/usds/simplereport/service/model/SmsDeliveryResult.java:3]: discussion: Is there a better name for this class? I am simultaneously working on #1931 which gets adds a webhook for Twilio to inform us of the message status as it gets enqueued, sent, and received.

File: backend/src/main/java/gov/cdc/usds/simplereport/service/sms/SmsService.java [hunk 7]
```diff
@@ -46,17 +49,46 @@ void init() throws NumberParseException {
...
   }
 
-  private String sendToPerson(Person p, String text) throws NumberParseException {
-    String msgId = sms.send(new PhoneNumber(formatNumber(p.getTelephone())), fromNumber, text);
-    LOG.debug("SMS send initiated {}", msgId);
-    return msgId;
+  private List<SmsDeliveryResult> sendToPerson(Person p, String text) {
+    List<SmsDeliveryResult> smsSendResults = new ArrayList<>();
+
+    p.getPhoneNumbers().stream()
```
Comment (nickscialli-usds) [inline backend/src/main/java/gov/cdc/usds/simplereport/service/sms/SmsService.java:72]: **question:** should this be filtered down to only the `MOBILE` type of phone numbers?

File: backend/src/test/java/gov/cdc/usds/simplereport/service/sms/SmsServiceTest.java [hunk 8]
```diff
@@ -150,4 +166,53 @@ void sendPatientLinkSmsUpdatesPatientLinkExpiry() throws NumberParseException {
...
+    // THEN
+    assertEquals(1, sut.size());
+    var result = sut.get(0);
+    assertEquals(_person.getPrimaryPhone().getNumber(), result.getTelephone());
+    assertEquals("some-twilio-id-10", result.getMessageId());
+    assertEquals(true, result.getDeliverySuccess());
+  }
+
+  @Test
+  @WithSimpleReportStandardAllFacilitiesUser
```
Comment (nickscialli-usds) [inline backend/src/test/java/gov/cdc/usds/simplereport/service/sms/SmsServiceTest.java:192]: **suggestion:** consider adding both land and mobile numbers and confirming text messages are only attempted to be sent to mobile numbers

File: frontend/src/app/testQueue/AoEForm/AoEForm.tsx [hunk 9]
```diff
@@ -276,13 +291,15 @@ const AoEForm: React.FC<Props> = ({
...
-              onChange={setTestResultDelivery}
-              buttons={getTestResultDeliveryPreferences(patient.telephone)}
-              selectedRadio={testResultDelivery}
-            />
+            <div className="prime-formgroup__wrapper">
+              <RadioGroup
+                legend="Would you like to receive a copy of your results via text message?"
+                name="testResultDelivery"
+                onChange={setTestResultDelivery}
+                buttons={getTestResultDeliveryPreferences(patient.phoneNumbers)}
```
Comment (nickscialli-usds) [inline frontend/src/app/testQueue/AoEForm/AoEForm.tsx:299]: **question:** will this be limited to display mobile numbers?

**Review by nickscialli-usds — COMMENTED** [review]
Looks great! Biggest question, which is why I didn't yet approve, is whether this is filtering out land lines when attempting to send messages.

File: backend/src/main/java/gov/cdc/usds/simplereport/service/sms/SmsService.java (hunk 1 above)
Comment (nathancrtr) [reply backend/src/main/java/gov/cdc/usds/simplereport/service/sms/SmsService.java]: Indeed it would! I was initially grossed out at the side-effect of sending the text message inside a `map()`, but given that it returns a usable value makes me feel OK about it. See 7fb7c8d.

File: frontend/src/app/testQueue/addToQueue/AddToQueueSearch.tsx (hunk 4 above)
Comment (nathancrtr) [reply frontend/src/app/testQueue/addToQueue/AddToQueueSearch.tsx:51]: See af59342 for an attempt to address this by adding a data loader for patient phone numbers.

File: backend/src/main/java/gov/cdc/usds/simplereport/service/sms/SmsService.java (hunk 7 above)
Comment (nathancrtr) [reply backend/src/main/java/gov/cdc/usds/simplereport/service/sms/SmsService.java]: Inspecting the acceptance criteria more closely 🕵️‍♂️, they do in fact say to:

> [...] update the question text to asks users if they would like to text all or none of the **mobile numbers.**

So, I'm going to say "yes". @aliciabeckett-gov can you confirm? It would certainly make sense.

File: backend/src/main/java/gov/cdc/usds/simplereport/service/model/SmsDeliveryResult.java (hunk 6 above)
Comment (nathancrtr) [reply backend/src/main/java/gov/cdc/usds/simplereport/service/model/SmsDeliveryResult.java:3]: Good call-out. Maybe something like `PatientLinkSmsDeliveryResult` sufficiently narrows the scope? It's a bit tricky to fully disambiguate since the class you'll be adding in #1931 could _also_ represent a "patient link SMS delivery result". What do you think?

Comment (nickscialli-usds) [reply backend/src/main/java/gov/cdc/usds/simplereport/service/model/SmsDeliveryResult.java:3]: It's something like `SmsAPICallResult` I think. The word that I think should probably not be in the name is "Delivery" because the success of the API call doesn't really speak to the delivery status.

File: frontend/src/app/testQueue/addToQueue/AddToQueueSearch.tsx (hunk 4 above)
Comment (nullflux) [reply frontend/src/app/testQueue/addToQueue/AddToQueueSearch.tsx:51]: Looks good!

File: backend/src/main/java/gov/cdc/usds/simplereport/service/model/SmsDeliveryResult.java (hunk 5 above)
Comment (nathancrtr) [reply backend/src/main/java/gov/cdc/usds/simplereport/service/model/SmsDeliveryResult.java]: Good call, changed in 97cfa11.

File: backend/src/main/java/gov/cdc/usds/simplereport/service/model/SmsDeliveryResult.java (hunk 6 above)
Comment (nathancrtr) [reply backend/src/main/java/gov/cdc/usds/simplereport/service/model/SmsDeliveryResult.java]: Addressed in c5a4c27.

File: frontend/src/app/testQueue/AoEForm/AoEForm.tsx (hunk 9 above)
Comment (nathancrtr) [reply frontend/src/app/testQueue/AoEForm/AoEForm.tsx]: Yes! Or, more specifically, non-landline numbers, per the [spec](https://docs.google.com/document/d/1Vk42CMKEtrFKqBbdPiz6JJ_uzB_RCsabqH2uFmwfPZE/edit).

>  If we don’t know if a number is mobile or landline, we should still display the number here.

Addressed in e772437.

File: backend/src/main/java/gov/cdc/usds/simplereport/service/sms/SmsService.java (hunk 7 above)
Comment (nathancrtr) [reply backend/src/main/java/gov/cdc/usds/simplereport/service/sms/SmsService.java]: Done in c5a4c27.

File: backend/src/test/java/gov/cdc/usds/simplereport/service/sms/SmsServiceTest.java (hunk 8 above)
Comment (nathancrtr) [reply backend/src/test/java/gov/cdc/usds/simplereport/service/sms/SmsServiceTest.java:194]: Excellent call 🦖 

Resolved by a8afe79.
