### PR TITLE
fix results page redirect loop

### LINKED ISSUE #2553: [BUG] Test results view causes a redirect loop
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

changing facility in test results view causes a redirect loop

### Steps To Reproduce

1. open test results page
2. change facility
3. observe the redirect loop

### Expected Behavior

no redirect loop and facility changes

### Additional context

https://user-images.githubusercontent.com/4952042/133323852-7b5f41e2-54a0-4c36-a509-54954f12fd12.mp4

### Does this issue have a priority label?

- [X] I have added a priority label

### Has issue been assigned to a team?

- [X] I have added a team label

### PR DESCRIPTION
**Pull request by zdeveloper**
## Related Issue or Background Info

- fixes #2553

## Changes Proposed
- add a new route that removed the filter search params
- remove clearing search params when un-mounting test results component

### UI
- [ ] Any changes to the UI/UX are approved by design 
- [ ] Any new or updated content (e.g. error messages) are approved by design 

### Testing
- [ ] Includes a summary of what a code reviewer should verify

### Changes are Backwards Compatible
- [ ] Database changes are submitted as a separate PR
  - [ ] Any new tables that do not contain PII are accompanied by a GRANT SELECT to the no-PHI user
  - [ ] Any changes to tables that have custom no-PHI views are accompanied by changes to those views
        (including re-granting permission to the no-PHI user if need be)
  - [ ] Liquibase rollback has been tested locally using `./gradlew liquibaseRollbackSQL` or `liquibaseRollback`
- [ ] GraphQL schema changes are backward compatible with older version of the front-end

### Security
- [ ] Changes with security implications have been approved by a security engineer (changes to  authentication, encryption, handling of PII, etc.)
- [ ] Any dependencies introduced have been vetted and discussed

## Cloud
- [ ] DevOps team has been notified if PR requires ops support
- [ ] If there are changes that cannot be tested locally, this has been deployed to our Azure `test`, `dev`, or `pentest` environment for verification

### CODE REVIEW

**Review by emmastephenson — APPROVED** [review]
LGTM, thanks for pushing out a fix!

File: frontend/src/app/commonComponents/ProtectedRoute.tsx [hunk 1]
```diff
@@ -9,6 +9,7 @@ interface Props {
   path: string;
   component?: React.FC<any>;
   render?: any;
+  exact?: boolean;
```
Comment (nickclyde) [inline frontend/src/app/commonComponents/ProtectedRoute.tsx:12]: Does this prop need to be passed to the `Route` component below?

File: frontend/src/app/App.tsx [hunk 2]
```diff
@@ -118,12 +120,20 @@ const App = () => {
...
             <ProtectedRoute
-              path="/results/:page?"
+              path="/results/"
+              render={() => <CleanTestResultsList />}
+              requiredPermissions={appPermissions.results.canView}
+              userPermissions={data.whoami.permissions}
+              exact={true}
+            />
+            <ProtectedRoute
+              path="/results/:page"
```
Comment (nickclyde) [inline frontend/src/app/App.tsx:130]: Another option here instead of passing `exact` through is to put the route with `:page` first, so that the more specific route gets matched first:
https://reactrouter.com/web/guides/primary-components

**Review by nickclyde — APPROVED** [review]
Just a few minor comments about using `exact`, otherwise looks good!

File: frontend/src/app/commonComponents/ProtectedRoute.tsx (hunk 1 above)
Comment (zdeveloper) [reply frontend/src/app/commonComponents/ProtectedRoute.tsx:12]: yes, without exact it matches /results with /results/:page and vice versa

File: frontend/src/app/App.tsx (hunk 2 above)
Comment (zdeveloper) [reply frontend/src/app/App.tsx:129]: yeah but that would be order dependent, meaning any harmless reorder might cause a functional issue

Comment (zdeveloper) [reply frontend/src/app/App.tsx:122]: made the change

File: frontend/src/app/testResults/CleanTestResultsList.test.tsx [hunk 3]
```diff
@@ -0,0 +1,54 @@
...
+
+const mockPush = jest.fn();
+jest.mock("react-router-dom", () => ({
+  useHistory: () => ({
+    push: mockPush,
+  }),
+}));
+
+describe("CleanTestResultsList", () => {
+  it("should redirect to page 1 of test results", async () => {
```
Comment (nickclyde) [inline frontend/src/app/testResults/CleanTestResultsList.test.tsx:34]: Awesome, thanks for the test!

**Review by nickclyde — APPROVED** [review]
