### PR TITLE
CSV Uploader Error handling improvements

### LINKED ISSUE #4235: Add alerts to failed result csv upload
### WHY?
we want to get pager duty alerts when we have upload failure event (RS) 

### Additional context
https://github.com/CDCgov/prime-simplereport/blob/db003727dddedb59e78f4fdbb1bf747716a1434d/ops/services/app_functions/report_stream_batched_publisher/functions/QueueBatchedReportStreamUploader/index.ts#L45-L54

Validation error event should have a different non-urgent alert vs. upload failure event (this one we would want to know about, means something is wrong with connection with RS). 

Do something similar to how it works for app itself.

### LINKED ISSUE #4633: Show errors for failed submissions to ReportStream
During the ReportStream outage, our ~uploader function~ csv file upload feature was getting responses from ReportStream in a shape we don't expect.
@DanielSass and I discussed and we think it would be good to double-check that we don't fail silently when ReportStream is down. Right now we only surface an error message if the errors field in the response from our backend is populated, and I don't think that's the case if we get a non-200 response from ReportStream.

Example response 1:
status: 504
body:  
```
<HTML><HEAD>
<TITLE>Gateway Timeout - In read </TITLE>
</HEAD><BODY>
<H1>Gateway Timeout</H1>
The proxy server did not receive a timely response from the upstream server.<P>
Reference&#32;&#35;1&#46;136bdc17&#46;1666816860&#46;528d7d3c
</BODY></HTML>

```

Example response 2:
status: 500
body:  
```
{"error": "Internal error at 2022-10-26T20:34:45.809723Z"}
```

### PR DESCRIPTION
**Pull request by DanielSass**
# BACKEND PULL REQUEST

## Related Issue

- resolves #4633 
- resolves #4235  

## Changes Proposed

- When we get an unreadable response from RS, return a 5xx error to the frontend, so errors are displayed correctly.

## Additional Information

- This isn't a front end change, but it updates to align to what the frontend is expecting (thus the screenshots)

## Testing

- For local manual verification I just butchered the RS url and tried to submit a file.  Screenshot below.
Screen Shot 2022-10-31 at 3 17 44 PM

### CODE REVIEW

File: backend/src/main/java/gov/cdc/usds/simplereport/service/TestResultUploadService.java [hunk 1]
```diff
@@ -87,7 +89,7 @@ public TestResultUpload processResultCSV(InputStream csvStream) {
         testResultFileValidator.validate(new ByteArrayInputStream(content));
     if (!errors.isEmpty()) {
       result.setErrors(errors.toArray(FeedbackMessage[]::new));
-      return result;
+      return new ResponseEntity<>(result, HttpStatus.OK); // should return bad request?
     }
```
Comment (DanielSass) [inline backend/src/main/java/gov/cdc/usds/simplereport/service/TestResultUploadService.java:93]: @zdeveloper do you have an opinion on this?

Comment (DanielSass) [reply backend/src/main/java/gov/cdc/usds/simplereport/service/TestResultUploadService.java:93]: (meaning should a validation failure be a 400 or should we just leave it as-is)

Comment (zdeveloper) [reply backend/src/main/java/gov/cdc/usds/simplereport/service/TestResultUploadService.java:93]: I dont think the service should return a ResponseEntity, since its a controller concept. I think it should throw a custom exception e.g. _CsvProcessingException_ and notice how it sets the response code `@ResponseStatus(HttpStatus.BAD_REQUEST)`

File: ops/services/alerts/app_service_metrics/main.tf [hunk 2]
```diff
@@ -253,3 +253,33 @@ ${local.skip_on_weekends}
     action_group = var.action_group_ids
   }
 }
+
+resource "azurerm_monitor_scheduled_query_rules_alert" "bulk_results_upload" {
+  name                = "${var.env}-bulk_results_upload"
+  description         = "${local.env_title} alert when bulk uploads "
```
Comment (nathancrtr) [inline ops/services/alerts/app_service_metrics/main.tf:259]: Is this description unfinished?

Comment (DanielSass) [reply ops/services/alerts/app_service_metrics/main.tf:259]: yes

Comment (zdeveloper) [reply ops/services/alerts/app_service_metrics/main.tf:259]: lol the description leaves you wanting more

**Review by emmastephenson — APPROVED** [review]
LGTM, the alert threshold is aggressive but I think that's warranted. Just hope ReportStream doesn't go down anytime soon 😄

File: ops/services/alerts/app_service_metrics/main.tf [hunk 3]
```diff
@@ -253,3 +253,33 @@ ${local.skip_on_weekends}
...
+    and name == "/upload/results"
+    and toint(resultCode) >= 500
+  QUERY
+
+  severity    = 1
+  frequency   = 5
+  time_window = 5
+  trigger {
+    operator  = "GreaterThan"
+    threshold = 0
```
Comment (alismx) [inline ops/services/alerts/app_service_metrics/main.tf:283]: Outside of the report stream outage, do we have any instances where this alert would have fired? How often?

I see you added the time window and the timestamp in the query :smile: :watch:

Comment (DanielSass) [reply ops/services/alerts/app_service_metrics/main.tf:283]: To be more specific - I ran a query for the last 7 days and didn't see any occurrences where this error would have fired. (In addition to running it during the RS outage)

Comment (DanielSass) [reply ops/services/alerts/app_service_metrics/main.tf:283]: Normally I would just assume that I butchered the query, but I did find the one instance during the outage 🙃

Comment (alismx) [reply ops/services/alerts/app_service_metrics/main.tf:283]: `time_window` is part of the scheduled alert config. `time_window` informs the alert how far back it should go to gather data. Without the timestamp in your query, your query runs against all the data available in that window. Adding the timestamp is an additional filter on the data.

**Review by zdeveloper — DISMISSED** [review]
LGTM! thank you for making this change

File: ops/services/alerts/app_service_metrics/main.tf [hunk 4]
```diff
@@ -253,3 +253,33 @@ ${local.skip_on_weekends}
...
+  action {
+    action_group = var.action_group_ids
+  }
+
+  data_source_id = var.app_insights_id
+  enabled        = contains(var.disabled_alerts, "bulk_results_upload") ? false : true
+
+  query = <<-QUERY
+requests
+| where true
```
Comment (mehansen) [inline ops/services/alerts/app_service_metrics/main.tf:272]: is this doing something?

File: ops/services/alerts/app_service_metrics/main.tf [hunk 5]
```diff
@@ -253,3 +253,33 @@ ${local.skip_on_weekends}
...
+| where timestamp >= ago(5m)
+    and name == "/upload/results"
+    and toint(resultCode) >= 500
+  QUERY
+
+  severity    = 1
+  frequency   = 5
+  time_window = 5
```
Comment (mehansen) [inline ops/services/alerts/app_service_metrics/main.tf:280]: nit: if `frequency` = `time_window` and the timestamp filter, is there a small chance something could slip through the cracks if there's any slight variation in fire time?
I noticed for the batched uploader failures we have a window of 11 min - not sure if that's why

**Review by mehansen — APPROVED** [review]
lgtm! have some non-blocking questions

File: ops/services/alerts/app_service_metrics/main.tf (hunk 4 above)
Comment (DanielSass) [reply ops/services/alerts/app_service_metrics/main.tf:272]: I DON'T KNOW!  But I see this in a lot of our queries so I added it in mine.

File: ops/services/alerts/app_service_metrics/main.tf (hunk 5 above)
Comment (DanielSass) [reply ops/services/alerts/app_service_metrics/main.tf]: That seems like a thing that could happen.

File: ops/services/alerts/app_service_metrics/main.tf (hunk 4 above)
Comment (mehansen) [reply ops/services/alerts/app_service_metrics/main.tf:272]: 😂  I assumed it was when `skip_on_weekends` gets evaluated in a query

**Review by emmastephenson — APPROVED** [review]

**Review by mehansen — APPROVED** [review]

File: ops/services/alerts/app_service_metrics/main.tf (hunk 4 above)
Comment (alismx) [reply ops/services/alerts/app_service_metrics/main.tf:272]: I am fairly certain that it's not doing anything.
