### PR TITLE
disallow invalid zipcodes when doing a bulkupload

### LINKED ISSUE #3111: Don't allow invalid zip codes during a bulk upload
### Description
Our bulk upload is not properly checking zipcodes

### Proposed solution 
please use the following regex 
```
^[0-9]{5}(?:-[0-9]{4})?$
^           # Assert position at the beginning of the string.
[0-9]{5}    # Match a digit, exactly five times.
(?:         # Group but don't capture:
  -         #   Match a literal "-".
  [0-9]{4}  #   Match a digit, exactly four times.
)           # End the noncapturing group.
  ?         #   Make the group optional.
$           # Assert position at the end of the string.
```
### Additional context
Hoping this will catch issues with bulk uploads that have incorrect zipcodes due to excel (or numbers) removing the leading zero of a zipcode.

### PR DESCRIPTION
**Pull request by zdeveloper**
## Related Issue or Background Info

- fixes #3111 

## Changes Proposed

- disallow invalid zipcodes during a bulkupload

### UI
- [x] Any changes to the UI/UX are approved by design 
- [x] Any new or updated content (e.g. error messages) are approved by design 

### Testing
- [x] Includes a summary of what a code reviewer should verify

### Changes are Backwards Compatible
- [x] Database changes are submitted as a separate PR
  - [x] Any new tables that do not contain PII are accompanied by a GRANT SELECT to the no-PHI user
  - [x] Any changes to tables that have custom no-PHI views are accompanied by changes to those views
        (including re-granting permission to the no-PHI user if need be)
  - [x] Liquibase rollback has been tested locally using `./gradlew liquibaseRollbackSQL` or `liquibaseRollback`
  - [x] Each new changeset has a corresponding [tag](https://docs.liquibase.com/change-types/community/tag-database.html)
- [x] GraphQL schema changes are backward compatible with older version of the front-end

### Security
- [x] Changes with security implications have been approved by a security engineer (changes to  authentication, encryption, handling of PII, etc.)
- [x] Any dependencies introduced have been vetted and discussed

## Cloud
- [x] DevOps team has been notified if PR requires ops support
- [x] If there are changes that cannot be tested locally, this has been deployed to our Azure `test`, `dev`, or `pentest` environment for verification

### CODE REVIEW

File: backend/src/test/java/gov/cdc/usds/simplereport/service/UploadServiceTest.java [hunk 1]
```diff
@@ -48,132 +44,139 @@ void setupData() {
...
     String value = this._service.getRow(Map.of("key1", "value1"), "key1", true);
-    assertEquals("value1", value);
+    assertThat(value).isEqualTo("value1");
   }
 
   @Test
   void testRowWithEmptyValue() {
     String value = this._service.getRow(Map.of("key1", ""), "key1", false);
-    assertEquals("", value);
+    assertThat(value).isEqualTo("");
```
Comment (emmastephenson) [inline backend/src/test/java/gov/cdc/usds/simplereport/service/UploadServiceTest.java:53]: Just a heads up that Sonar is flagging this as a code smell; it wants you to use `isEmpty()` instead

File: backend/src/test/java/gov/cdc/usds/simplereport/service/UploadServiceTest.java [hunk 2]
```diff
@@ -48,132 +44,139 @@ void setupData() {
...
-    }
-
-    final List<Person> patients =
-        this._ps.getPatients(null, PATIENT_PAGEOFFSET, PATIENT_PAGESIZE, false, null);
-    assertAll(
-        () -> assertEquals(1, patients.size()),
-        () -> assertEquals("Best", patients.get(0).getLastName()),
-        () ->
-            assertEquals(address, patients.get(0).getAddress(), "Should have the correct address"));
+  void testUploadValidCsv() {
```
Comment (emmastephenson) [inline backend/src/test/java/gov/cdc/usds/simplereport/service/UploadServiceTest.java:64]: Thanks for updating all these tests, they look great!

**Review by emmastephenson — APPROVED** [review]
LGTM!

File: backend/src/test/java/gov/cdc/usds/simplereport/service/UploadServiceTest.java (hunk 1 above)
Comment (zdeveloper) [reply backend/src/test/java/gov/cdc/usds/simplereport/service/UploadServiceTest.java:53]: Honestly I kinda prefer to check that its putting out exactly `""`, isEmpty() is probably that exact same but I like to be explicit

Comment (emmastephenson) [reply backend/src/test/java/gov/cdc/usds/simplereport/service/UploadServiceTest.java:53]: Fair enough! Just wanted to flag it

**Review by emmastephenson — APPROVED** [review]

**Review by nathancrtr — APPROVED** [review]
I attempted a bulk upload using the "invalid zip code" CSV that you included as a part of this PR and got the expect error. LGTM!
