### PR TITLE
Prevent onChange during PersonForm form initialization

### LINKED ISSUE #2280: [BUG] Edit patient warning that "your changes have not been saved" always appears, even if no changes have been made
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

warning that "your changes have not been saved" always appears, even if no changes have been made.

### Steps To Reproduce

click into a (valid) person, don't make any changes, and click the breadcrumb back to "people"

### Expected Behavior

The modal warning should not appear if no changes have been made to the form.

### Additional context

Note: we should verify that this also happens in the production environment, since I only tried on dev.

### Does this issue have a priority label?

- [X] I have added a priority label

### Has issue been assigned to a team?

- [X] I have added a team label

### PR DESCRIPTION
**Pull request by nickscialli-usds**
## Related Issue or Background Info

- Closes #2280

## Changes Proposed

The `ComboBox` component taken from the Truss component library fires an `onChange` event when mounting. To prevent this from marking our form as "dirty," this PR does a quick PR to check if the new value is different from the old value.

### UI
- [n/a] Any changes to the UI/UX are approved by design 
- [n/a] Any new or updated content (e.g. error messages) are approved by design 

### Testing
- [n/a] Includes a summary of what a code reviewer should verify

### Changes are Backwards Compatible
- [n/a] Database changes are submitted as a separate PR
  - [n/a] Any new tables that do not contain PII are accompanied by a GRANT SELECT to the no-PHI user
  - [n/a] Any changes to tables that have custom no-PHI views are accompanied by changes to those views
        (including re-granting permission to the no-PHI user if need be)
  - [n/a] Liquibase rollback has been tested locally using `./gradlew liquibaseRollbackSQL` or `liquibaseRollback`
- [n/a] GraphQL schema changes are backward compatible with older version of the front-end

### Security
- [n/a] Changes with security implications have been approved by a security engineer (changes to  authentication, encryption, handling of PII, etc.)
- [n/a] Any dependencies introduced have been vetted and discussed

## Cloud
- [n/a] DevOps team has been notified if PR requires ops support
- [n/a] If there are changes that cannot be tested locally, this has been deployed to our Azure `test` environment for verification

### CODE REVIEW

File: frontend/src/app/constants/constants.d.ts [hunk 1]
```diff
@@ -589,7 +589,7 @@ interface PersonUpdate extends Address {
   gender: Gender;
   residentCongregateSetting: boolean | null | undefined;
   employedInHealthcare: boolean | null | undefined;
-  tribalAffiliation: TribalAffiliation;
+  tribalAffiliation: TribalAffiliation | undefined;
```
Comment (jdorothy) [inline frontend/src/app/constants/constants.d.ts:592]: Did this PR get another bug fix mixed into it? What's happening with `tribalAffiliation`?

Comment (nickscialli-usds) [reply frontend/src/app/constants/constants.d.ts:592]: This is actually the same bug. Since we weren't allowing `tribalAffiliation` to be `undefined` (it _should_ be allowed to be undefined), we had been setting it to a default value (`null`) in `PersonForm`. The `ComboBox` component, which is from the React USWDS maintained by Truss, only takes a `string` or `undefined` type as its value. We were therefore assigning its value as `patient.tribalAffiliation || undefined`. The `ComboBox` fires an initial `onChange` event, which we can safely ignore if the changed value is equal to the previous value, but in the case of `tribalAffiliation` the changed value was `undefined` and previous value was `null`. By allowing `tribalAffiliation` to be initialized as `undefined`, we can safely ignore the initial `ComboBox` `onChange` event that was causing the form to be marked as dirty.

Comment (jdorothy) [reply frontend/src/app/constants/constants.d.ts:592]: Got it - thanks!

**Review by bmaden-usds — APPROVED** [review]
Looks good, thanks!  It will be really nice to have this fixed
