### PR TITLE
Elisa/6929 result notification bug

### LINKED ISSUE #6929: [BUG] Updating how a patient would like to receive results does not save properly when clicking save and start test
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When updating the fields "Would you like to receive your results via text message?" / "Would you like your test result sent to this email?" and then clicking "Save and start test", those fields cannot be set to "Yes" and if one field is set to "No" both get set to "No". If you press "Save" it works fine.

Here are the combos:
1. Both Set to "No" - Change both to "Yes" - **Both are "No"**
2. Both Set to "Yes" - Change both to "No" - Both get updated to "No"
3. Both Set to "Yes" - Change one to "No" - **Both get updated to "No"**
4. One set to "No" - Change to "Yes" - **Set to "No"**
5. One set to "Yes" - Change to "No" - Gets set to "No"
6. One "Yes", One "No" - Change "Yes" to "No" and "No" to "Yes" - **Both are "No"**

Some videos below in additional context

### Steps To Reproduce

1. Go to patients page
2. Edit a patient with ""Would you like to receive your results via text message" set to no
3. Update "Would you like to receive your results via text message" to Yes
4. Save and Start Test
5. View patient and confirm it is still no

### Expected Behavior

Whatever is selected gets saved

## Not working
Updating both to "Yes"

https://github.com/CDCgov/prime-simplereport/assets/10108172/19d6bf30-18af-4814-a337-a598688c9adf

Update one to "Yes"

https://github.com/CDCgov/prime-simplereport/assets/10108172/34b0f1c3-59d3-48dc-80f0-a8db2f924e6e

Selecting No on one of the fields will set both to No

https://github.com/CDCgov/prime-simplereport/assets/10108172/4b9b1c00-eb3b-4283-93e0-0c354319ff33

## Working
If a test is already in progress the save works as expected.

https://github.com/CDCgov/prime-simplereport/assets/10108172/eb6eb0be-53e1-4fb6-9335-3e8c6e1f0dd6

Update to "No"

https://github.com/CDCgov/prime-simplereport/assets/10108172/eec888a1-425c-493b-8a07-a933c5b36e28

Just "save" works fine in all combos

https://github.com/CDCgov/prime-simplereport/assets/10108172/39b4f786-b860-4cd2-8186-c0691e6f415a

### Does this issue have a priority label?

- [X] I have added a priority label

### Has issue been assigned to a team?

- [X] I have added a team label

### PR DESCRIPTION
**Pull request by emyl3**
# PULL REQUEST

## Related Issue

Partially resolves #6929

## Changes Proposed

- Fixes the bug where test result notification preferences were not being saved when a patient was added to the queue or their AOE question was being updated

## Additional Information
- in a separate PR, once #7014 is merged in will make sure this is covered in the e2e test

## Testing
- Ensure a patient's test result delivery preferences save even if they are added to the queue or their AOE questions are updated
- available on dev4 for testing with the new card refactor
- available on dev2 for testing with the old test cards

### CODE REVIEW

File: frontend/src/app/testQueue/TestCardForm/TestCardForm.tsx [hunk 1]
```diff
@@ -201,6 +201,7 @@ const TestCardForm = ({
         pregnancy: state.aoeResponses.pregnancy,
         genderOfSexualPartners:
           state.aoeResponses.genderOfSexualPartners ?? null,
+        testResultDelivery: testOrder.patient.testResultDelivery ?? null,
```
Comment (mpbrown) [inline frontend/src/app/testQueue/TestCardForm/TestCardForm.tsx:204]: **question** - why are we adding this back onto the mutation here? The new design for AOE questions doesn't allow the user to change delivery preferences outside of the `EditPatient` page. The `updateTimeOfTestQuestions` mutation is still being used by the old test card design so that's why the test result delivery logic in that mutation hasn't been removed yet, but I wonder if part of this bug is that the mutation is overriding the test result delivery preference as null when it isn't provided by the new test card, so perhaps we should add a null check for that here

```
@MutationMapping
  public void updateTimeOfTestQuestions(
      @Argument UUID patientId,
      @Argument String pregnancy,
      @Argument String symptoms,
      @Argument LocalDate symptomOnset,
      @Argument Boolean noSymptoms,
      @Argument List<String> genderOfSexualPartners,
      @Argument TestResultDeliveryPreference testResultDelivery) {

    Map<String, Boolean> symptomsMap = parseSymptoms(symptoms);

    testOrderService.updateTimeOfTestQuestions(
        patientId, pregnancy, symptomsMap, symptomOnset, noSymptoms, genderOfSexualPartners);

    if (testResultDelivery != null) {
      personService.updateTestResultDeliveryPreference(patientId, testResultDelivery);
    }
  }
```

**Review by mpbrown — CHANGES_REQUESTED** [review]
Left a question and suggested change about the `updateTimeOfTestQuestions` mutation, let me know what you think!

File: frontend/src/app/testQueue/TestCardForm/TestCardForm.tsx (hunk 1 above)
Comment (emyl3) [reply frontend/src/app/testQueue/TestCardForm/TestCardForm.tsx:204]: Yes! that's exactly what was happening! I like addressing this on the backend. Thank you for the question/suggestion mike! Will update this on `updateTimeOfTestQuestions` and `addPatientToQueue` as well. :)

**Comment by emyl3** [comment]
editing based on mike's feedback please do not review :D

**Comment by emyl3** [comment]
@fzhao99 @mpbrown ready for re-review! :)

dev2 has the old test card for testing
dev4 has the new test card

**Review by mpbrown — APPROVED** [review]
Tested in dev2 and dev4 and LGTM!

**Review by fzhao99 — APPROVED** [review]
lgtm!
