### PR TITLE
Fix Empty Syphilis Symptoms View

### LINKED ISSUE #7901: Show syphilis symptoms in result view
### Description

It looks like we are missing some logic to handle the syphilis symptoms when viewing a syphilis result.
See screenshot for a result for patient where I checked the boxes for all symptoms:
Screenshot 2024-07-10 at 2 55 14 PM

### Expected behavior

The symptoms stored on the test event should be listed in the result details view.

### Action requested

Update the frontend to fix the bug.
Update the [new disease documentation](https://docs.google.com/document/d/1DWAc8vCng2daAA7cKdpe8O6ViMB28uqOpjemQKvpv3s/edit?usp=sharing) to cover what we need to do in the future if we have new AOE symptoms to track.

### PR DESCRIPTION
**Pull request by bobbywells52**
# FRONTEND PULL REQUEST

## Related Issue

- Resolves #7901 

## Changes Proposed

- Create an`AllSymptoms` type system and update the `symptomsStringToArray` function to return a type of `AllSymptomsName[]` instead of just a `RespiratorySymptomName[]`.

- Create an `allSymptomsMap` for `symptomsStringToArray` to utilize instead of only referencing against the `respiratorySymptomsMap`.

## Testing

1. Conduct a postive test with the syphilis device in dev6
2. Verify that syphilis symptoms are being displayed in the result view for the test

## Screenshots / Demos

Screenshot 2024-08-21 at 1 58 43 PM

### CODE REVIEW

File: frontend/src/patientApp/timeOfTest/constants.ts [hunk 1]
```diff
@@ -134,3 +135,38 @@ export const syphilisSymptomDefinitions: SymptomDefinitionMap[] =
 export const SYMPTOM_SUBQUESTION_ERROR =
   "This question is required if the patient has symptoms.";
 export const ONSET_DATE_LABEL = "When did the patient's symptoms start?";
+
+export type AllSymptomsCode = keyof RespiratorySymptoms &
+  keyof SyphilisSymptoms;
+export type AllSymptomsName = RespiratorySymptomName & SyphilisSymptomName;
+export const allSymptomsMap = {
```
Comment (bobbywells52) [inline frontend/src/patientApp/timeOfTest/constants.ts:142]: ⚠️ I tried to programmatically generate this map by combing the disease specific maps in code. However, since those maps are exported as constants they are defined as readonly. Because of this, I could not find a way programmatically generate an all symptoms map and instead just had to hard code this one.

Comment (bobbywells52) [reply frontend/src/patientApp/timeOfTest/constants.ts:142]: If someone does know a way to combine two readonly maps in code please lmk 😅

Comment (fzhao99) [reply frontend/src/patientApp/timeOfTest/constants.ts:142]: I think you can just do 

```
export const allSymptomsMap = {
  ...syphilisSymptomsMap,
  ...respiratorySymptomsMap,
};
```

Comment (bobbywells52) [reply frontend/src/patientApp/timeOfTest/constants.ts:142]: Wow idk how I missed that 🤦 -- updated

**Review by fzhao99 — APPROVED** [review]
lgtm!

**Review by emyl3 — APPROVED** [review]
LGTM! nice work!
