### PR TITLE
Avoid clicking twice on test queue Submit or Remove-X

### LINKED ISSUE #292: Clicking circle-X to remove an item from the queue crashes the app
In `dev` I clicked to remove an item from the queue and it didn't disappear immediately so I clicked it again. Got this error. Most likely cause is that the second click initiated a second delete request which found the cupboard bare. I'd like to fix two things here:
1. Clicking the delete button should disable it until the request completes (or in another way prevent dual submissions).
1. The backend should not error on a request to delete a record that isn't there, and just return a status indicating that it wasn't found.

```
 {
  "graphQLErrors": [
    {
      "message": "Exception while fetching data (/removePatientFromQueue) : No active test order was found for that patient",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "removePatientFromQueue"
      ],
      "extensions": {
        "classification": "DataFetchingException"
      }
    }
  ],
  "networkError": null,
  "message": "Exception while fetching data (/removePatientFromQueue) : No active test order was found for that patient"
} 
```

### PR DESCRIPTION
**Pull request by dmethvin-gov**
## Related Issue or Background Info

Fixes #292 

## Changes Proposed

* Disable the Submit button but re-enable if there is an error
* Disable the X delete but re-enable if there is an error
* Make a few types more strict
* Convert to a button to improve 508-ness
* Minimize verbosity in args passed to QueueItem

## Screenshots / Demos

No functional diff visually.

### CODE REVIEW

File: frontend/src/app/testQueue/QueueItem.tsx [hunk 1]
```diff
@@ -238,7 +239,11 @@ const QueueItem: any = ({
         .then(testResultsSubmitted)
         .then(refetchQueue)
         .then(() => removeTimer(internalId))
-        .catch((error) => updateMutationError(error));
+        .catch((error) => {
+          updateMutationError(error);
+          // Re-enable Submit in the hopes it will work
+          if (e) e.currentTarget.disabled = false;
```
Comment (dmethvin-gov) [inline frontend/src/app/testQueue/QueueItem.tsx:245]: There are a few situations where React might switch DOM elements on us and we'd have to track with a `useRef` but this didn't seem to be one of them (there is no re-render behind the modal dialog) so it should be fine.

**Review by timothybest-usds — APPROVED** [review]

**Comment by dmethvin-gov** [comment]
@TimBest I'll wait on this until you merge #393 because I installed the same deps as you for unit testing. Sometimes that creates a slightly different yarn lockfile and if we both merge via the GitHub UI it might mangle that. Once #393 is merged I'll rebase against that and things should be good.
